### ISSUE TITLE
Add LDAP lookup to PB API Mock Personnel

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#101]
It would be useful to be able to do LDAP lookup when adding personnel in the Protocol Builder API Mock.

**Comment by cullerton** [comment]
Added a livesearch with JQuery. Works for adding investigators too.

**Comment by calexh-sar** [comment]
@danfunk this is not working in Testing.  Has it been released yet?

**Comment by calexh-sar** [comment]
Done
