### ISSUE TITLE
Validate Hide Expressions

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#103]
During the workflow validation process, attempt to validate all hide expressions.
This is a bit tricky as the front end places the Task.data inside a "model".  So all references must be in the model, and the evaluation of the expressions currently get processed

**Comment by danfunk** [comment]
This might be done. It does take hide expressions into account.  @calexh-sar can you verify that this is still a problem?

**Comment by calexh-sar** [comment]
@danfunk and @cullerton , in the IND Info (ind_update.bpmn) workflow, the "Edit IND #3 Info" task has the Form Field "IND3_HolderNameOSP" which has the hide_expression Property `!model.IND3_HolderType || !model.IND3_HolderType.value || (model.IND3_HolderType.value !== "Industry" && model.IND3_HolderType.value !== "OtherCollUniv")`.  I would expect this should fail, but it passes the shield test.

**Comment by cullerton** [comment]
I don't think we ever evaluate the hide_expression in this workflow during the shield test. It appears the test never takes the =1(Yes) path out of the IS_IND gateway. 

I only see Show Contact Admin show up in populate_form_with_random_data. It shows up twice actually. The only two things that show up there.

**Comment by cullerton** [comment]
I changed the is_ind variable in study_info, and reran the shield test, which resulted in the expected behavior. 

--- We do check the hidden_expression, and it does fail.---

The reason it didn't work initially is because of how study_info details are set. We don't currently have a solution for this.

**Comment by calexh-sar** [comment]
Done
