### ISSUE TITLE
Single = not caught by shield in End Event

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#105]
I entered a single = in an End Event and it was not caught by the shield. Sentry returned a [TemplateSyntaxError](https://sentry.io/organizations/sartography/issues/1801286811/?referrer=slack) error.  No stack trace was returned.

**Comment by danfunk** [comment]
Not sure how to follow up on this.  Mike will follow up with Alex later to find a way to reproduce it.

**Comment by calexh-sar** [comment]
@cullerton In the Protocol Builder Data workflow (irb_api_details.bpmn) "From IRB API" task I changed one of the "==" in the Element Documentation to a "=" and ran the shield test and received the following error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/29181b7c-7687-4f86-8640-ed4f054fa2bb)

I fixed this and then copied the same code over to the End Event Element Documentation and ran the shield test, with no error message thrown.  I then changed the same "==" to "=" and ran the shield test and again no error thrown.  I left the workflow in this state.

**Comment by cullerton** [comment]
@calexh-sar What is End Event Element Documentation? Is this a workflow on https://testing.crconnect.uvadcos.io/bpmn/home?

**Comment by cullerton** [comment]
Sorry, @calexh-sar :(

I'm pretty sure you mean the End Event for that workflow.

**Comment by calexh-sar** [comment]
The Element Documentation field for the End Event can be found on the General tab.

Does this help?

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/e5208bfd-71d8-4635-8ff3-af0c646d51b5)

**Comment by cullerton** [comment]
Created branch verify-end-event-#105. Pull Requested.
