### ISSUE TITLE
augment Spiff Exec/eval namespace with StudyInfo method (and others) 

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#106]
This will allow us to call the script in the same way as we call other scripts and assign the result to variables.
(see code samples below) 
I am also changing the StudyInfo method to accept an optional parameter of a prefix to look for - and filter the results based on that prefix. 
 
At first I thought I would remove the shebang method, but at first I will just simply add the feature, and remove it at a later date if we want to. 

investigators = StudyInfo('investigators')
pi = StudyInfo('investigators','PI') ==> pi dict
scs = StudyInfo('investigators','SC_') ==> {'SC_1':,
'SC_':}

Ideally, this would also create them with the python-box feature as well if it is a dictionary.

**Comment by calexh-sar** [comment]
Confirmed this works with the following code updates:

investigators = study_info('investigators')
pi = study_info('investigators','PI')
scs = study_info('investigators','SC')
