### ISSUE TITLE
TaskData State & Recall

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#110]
Provide a means to determine from one workflow if another workflow has been completed and to pull its last task data for use in the current workflow.

An example of where  this would be used is to pull the Department Chair approver for current study.  The task data state would be used to determine if the Department Chair task has been saved and ready for use.

**Comment by danfunk** [comment]
Putting this in the ice-box, as I don't think we will implement this, relying on the data store, and possibly signal events across workflows.

**Comment by calexh-sar** [comment]
Closing this since we should be able to use Datastore variables to track which workflows are complete and pass data between them, as needed.
