### ISSUE TITLE
Prevent Duplicate Template File Upload

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#111]
The Configurator Tool allows for uploading a template file of the same name.  If there is a reason to allow this, it should prompt the user to make sure they want to proceed.  If this is not a reason to allow for this, problem the user that they will not be able to add another file of the same name and should be using the update process if that is what they wish to do.

**Comment by cullerton** [comment]
We now check whether a file already exists for that workflow_spec_id and name. If so, we raise an ApiError. Otherwise, we add the record as usual.

**Comment by calexh-sar** [comment]
Working as designed
