### ISSUE TITLE
Make read_only dynamic

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#114]
Per 08/05 post scrum discussion, make the read_only property dynamic so it can be set based on variable coming into the workflow and/or current form field settings.

**Comment by ajlouie** [comment]
Fixed by:
https://github.com/sartography/cr-connect-frontend/commit/c879719b64127e25cf9c910cc13e8d7e85d02bbf
https://github.com/sartography/cr-connect-frontend/commit/2bfab5e3b1d285ac7890fe283903904d06b5ecbc
https://github.com/sartography/cr-connect-frontend/commit/58b98ae0d1225fc07ae08a8f762088cdb138ee12

**Comment by calexh-sar** [comment]
Not sure if the dynamic part of this works or not because it seems that the static read_only is not working as it should.  I put a read_only property on a string field and when I set the Value of the Property to `True`, it worked as designed, the field on the for was read-only.  I think entered `False` as the Value, but the field remained read-only.  I think tried `1 == 1` and `1 == 2', both returned read-only.  It seems that regardless of what you enter in the Property Value field, the field is read-only.  If the Value is left blank, it is not read-only.  In all of these cases, the shield test passed.

**Comment by calexh-sar** [comment]
@NWalker4483 I am checking tickets in Ready for Release per discussion with Dan in which he said that there is noting pending for him to release and code for all tickets should be available in testing.

If this is indeed the case, this issue is still not fixed.

**Comment by calexh-sar** [comment]
@NWalker4483 the dynamic part of this is not working,
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a2a43568-fa3d-44ac-8b4b-daac90e9622a)
works, but
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ef40801d-8ecd-4361-9ed7-9876798919a5)
where
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/0601412e-045d-4d05-ab51-1a4e6bd2db24)
does not.

**Comment by calexh-sar** [comment]
@NWalker4483 since your availability is uncertain at this time, I am going to assign this ticket to @Leashys ,  She may be reaching out to you for some history updates.

**Comment by danfunk** [comment]
This will now work if you use 'read_only_expression' rather than just 'read_only'.  We might consider looking at all of these 'expression' based items.  I wonder if we really to have two calls, or if we could always evaluate everything, and make this easier to use.

**Comment by NWalker4483** [comment]
Yeah it makes no sense for this to be separate properties. There might be
some stragglers that have weird definitions like that too

**Comment by calexh-sar** [comment]
Created read_only_test in Alex's Tests and confirmed this is working as designed if your use `read_only_expression` for the dynamic ones.
