### ISSUE TITLE
Hiding field should not clear data until Save

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#115]
Per 08/05 post scrum discussion, when a field is hidden in a form and there is data in it, the data should not be cleared out until the form is saved.

**Comment by ajlouie** [comment]
Fixed by https://github.com/sartography/cr-connect-frontend/commit/059460a56ef0aa7a248d9c6307d07d26ff3a61c5

**Comment by calexh-sar** [comment]
Working as designed
