### ISSUE TITLE
Key-Value Data store Script Task 

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#119]
Add a script task that can save and restore values, allowing some data sharing between workflows.
The script should store the key and value - and it will return a value given a key.  Retrieving a value should take a default that it will return in the event that the value is not found in the data store.

The data store should provide the option to associate values with a study, workflow_id, workflow_spec_id, or none of the above - If we can handle that in a sensible way.

**Comment by calexh-sar** [comment]
Duplicate to #128
