### ISSUE TITLE
Add production instances of all services

### ISSUE THREAD

**Issue by ajlouie** [sartography/cr-connect#13]
- [ ] Production Protocol Builder API
- [ ] Database - db.crconnect.uvadcos.io
  - [ ] Block access to all except below
  - [ ] Allow access from Backend (api.crconnect.uvadcos.io) domain
  - [ ] Allow access by superuser NetBadge logins and valid API keys
- [ ] Backend - api.crconnect.uvadcos.io
  - [ ] Block access to all except below
  - [ ] Allow access from Configurator (bpmn.crconnect.uvadcos.io) domain
  - [ ] Allow access from Frontend (crconnect.uvadcos.io) domain
  - [ ] Allow access by superuser NetBadge logins and valid API keys
- [ ] Configurator - bpmn.crconnect.uvadcos.io
- [ ] Frontend - crconnect.uvadcos.io

**Comment by calexh-sar** [comment]
@danfunk and/or @w4kpm , has this ticket been satisfied by the work Elad and you did to be able to update instances, or is there still more to do?

**Comment by danfunk** [comment]
This is satisfied, through we need to get the production servers back online and ready with direct connections and good exports.  I'll be filing new tickets for these tasks.
