### ISSUE TITLE
Investigate shared decision tables

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#130]
Determine if the Business Rule task binding options remove or reduce the risk of real time updates for decision tables that are shared by multiple workflows.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/cfffb890-951f-41eb-bd59-9a97a2875791)

**Comment by danfunk** [comment]
Will be taken care of as a part of our shared libraries effort.
