### ISSUE TITLE
Dynamic Enum list example in Configurator's Guide does not work

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#131]
We should have any example in there that works.  Aaron spent some time on this, but was not able to come up with a working example where you can make a list from StudyInfo.  The only way to do it now is one row at a time.

**Comment by calexh-sar** [comment]
Mike provided two options similar to the example that should work:

**Option A**
```
sponsors = study_info("sponsors")
spon_enum = [{'value':sponsor['SPONSOR_ID'], 'label':sponsor['SP_NAME']} for sponsor in sponsors]
```

**Option B**
```
sponsors = study_info("sponsors")
spon_enum = []
for sponsor in sponsors:
    spon_enum.append({"value": sponsor['SPONSOR_ID'],"label": sponsor['SP_NAME']})
```

**Comment by cullerton** [comment]
@calexh-sar What do you want to do with this ticket?

**Comment by calexh-sar** [comment]
I put Option 1 in the wiki.
