### ISSUE TITLE
Spiff documentation 

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#135]
Get Spiff workflow documentation and examples up to date - ongoing issue

**Comment by w4kpm** [comment]
Things to document 
- [x] Simple web form
       add to data variable
- [x] documentation fields / jinja
- [x]  script & data variables
        talk about scripting and interaction within the namespace 
- [x] exclusive gateway
- [x] parallel gateway
- [x] SMI / PMI
- [x] lanes
- [x] edge events 
- [x] script extensions
- [x] decision tables
- [x] subprocess / both exapanded and external
- [x] nav list & lanes
- [x] serialize & deserialize

**Comment by w4kpm** [comment]
Hand off to Mike so that we can 

a) Get Mike up to speed on all things Spiff Related
b) Work through BPMN basics
c) Proofread and polish the documentation that has been done by Kenna and I
d) Perhaps smooth the transition to PyCharm

**Comment by calexh-sar** [comment]
Done for now, any updates and edits on new ticket.
