### ISSUE TITLE
Sequential MI UI Improvements

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#15]
When a sequential multi-instance loads, there is no indication of how may iterations of the current form the user will need to fill out to complete the task.  It would be preferable to have something in  the lines of "1/5 <whatever is being entered, or some generic text>" that refreshes to indicate which iteration of the sequence is being entered.

There is also no way to navigate back to a completed iteration if the need to review or change arises while completing the task.  This functionality would be nice to have.

And once all iterations have been entered, the final screen should show a recap of all iterations, similar to how we do with repeating sections (and I assume Looping once that is available).

**Comment by danfunk** [comment]
We should re-think multi-instance yet agian, and open a new ticket for how it should work in multiple cases.
