### ISSUE TITLE
BSNS Computer ID Search Expansion

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#169]
Meg and I just identified that for last week approximately 1% of the Computing IDs that were entered in the barcode did not match the Computing ID found at the beginning of the email address pulled from Ravi's file.  It appears that the one entered in the barcode is incorrect due to typo's and/or mis-communications.  Although this percentage is small, they potentially will be a higher percentage of support calls.  In order to work around this issue, search both the barcode and email fields for a match.

**Comment by NWalker4483** [comment]
Think I've got a fix do you have an example off hand?
