### ISSUE TITLE
Option to show current user studies only in PB Mock.

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#173]
As more studies are added to the Protocol Builder Mock app by multiple users, it would be beneficial to have a means for the current user to indicate they would like to see only studies they created.

**Comment by calexh-sar** [comment]
@cullerton When I click on the Select User dropdown  dropdown I still get redirected to: https://testing.crconnect.uvadcos.io/app/home.

Has the fix for this been released yet?

**Comment by cullerton** [comment]
@calexh-sar It's working for me on testing with Firefox.

Maybe we can look into this after scrum.

**Comment by cullerton** [comment]
Turns out the fix hasn't been merged yet.

**Comment by calexh-sar** [comment]
Working as desgned
