### ISSUE TITLE
Hidden fields with value_express should not be saved

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#174]
We made the decision a while ago that data from hidden fields would not be saved and if there was existing data from a previous save when the field was not hidden, it should be removed.  It appears that the current value_expression update might have changed this, or it is not happening across the board.

**Comment by cullerton** [comment]
It turns out, we don't actually save the default data. When fields are hidden, the values are set to null.

No code was changed working on this ticket.

Will send the ticket to Review/QA to make sure nothing pops up.
