### ISSUE TITLE
Improve error message for missing Condition Type

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#178]
Lydia had trouble understanding this error message:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/1c7581fa-47fc-49f1-affa-6b5781bde10c)

Which was the result of a missing Condition Type: 
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/1b26ab22-a34b-465d-a549-01505dc56842)

Can we do anything to be more specific about the cause of this error?

**Comment by calexh-sar** [comment]
@cullerton I set up a test where there was a missing ConditionType and got this error:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/cdc8b9f9-71b4-4568-8330-dc48bd0717c0)

This appears to be basically the same as before.  Did we decide not to do anything with this ticket?  Or perhaps it has not been released yet?  If none of those, let discuss what you have in mind.

**Comment by cullerton** [comment]
@calexh-sar This should have a hint associated with it that says "Add a Condition Type to your gateway path". Maybe the hints aren't showing up yet.

**Comment by cullerton** [comment]
@calexh-sar  I believe this is working.

**Comment by calexh-sar** [comment]
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/83f81d27-db59-48d5-8e2f-71737ff51a08)

Working as designed
