### ISSUE TITLE
Remove 'Total Tasks' and 'Completed Tasks' form workflows API on cr_connect_workflow and dependencies

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#179]
We are currently running through every workflow that a study references - instantiating it and determining the number of total tasks and remaining tasks.

This is running longer than we want it to and it is not always an accurate representation of what the state is.

We have decided that a study's progress will be measured in terms of workflows completed and remaining, rather than the number of tasks, so these extra steps will not be needed.

I have already removed the reference in one place in cr_connect workflow, but we need to make sure there are no more.

Also we need to remove it from the sartography_utils package

**Comment by w4kpm** [comment]
There was no value in removing these fields as they were taking straight off of the nav list - which we need for other things. It was determined that the risk of causing a problem somewhere was greater than the value of cleaning up these fields.

**Comment by danfunk** [comment]
closing per Kelly's comment. And I also verified that total_tasks no longer exists anywhere anyway.
