### ISSUE TITLE
Include information about reviews on the information that gets returned on the study.

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#182]
1) create a new field in the workflow_spec table marked has_review
2) whenever we create/save/update a workflow spec, we run a simple xpath query on the resulting xml to see if there is any swimlanes with 
    a name that is not blank. These were determined in a meeting (2/2/2021 ) to be the places where blocking reviews or approvals would 
   happen.
3) when we return all of the workflows, we will need to join the spec record and grab 'has_review' 
4) on the front end, we can determine the number of workflows with 'has_review' and also the number of workflows with this tag that are also 'COMPLETED' for a resulting approvals status to display.

**Comment by w4kpm** [comment]
This has been completed and is in review on both front end and back end.

**Comment by calexh-sar** [comment]
Working as designed.
