### ISSUE TITLE
When creating a new study - the study goes immediately to 'In Progress' - it should go to 'new' as a first step

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#184]
We have code in the frontend to show a study as 'NEW' with the row highlighted,

But when we copy over a new study from PB, it goes immediately to 'in progress' in the database.

While we could change the behavior of the frontend, it would be best to have the backend report the status of a study be 'NEW' until someone goes in and makes a change.

This would be a matter of :
1) making sure the status on the study is 'new' to start with
2) updating the study to be of status 'in_progress' if we update a task_event and the status is currently 'new' - we don't want to interfere with other status types
3) changing the status to 'new' may make it not show up in the 'in progress' tab, but I doubt we want to make a new tab for 'in progress'

If we decide to not do anything with the backend, we will need to have the last update code in place from ticket #180 - if we can pull a last status then it is not new, and if there are no task_events, then it is new.

**Comment by w4kpm** [comment]
We decided that we need to add another tab 'New' for all new processes - this takes care of #3 above

**Comment by cullerton** [comment]
@w4kpm @danfunk 

I'm confused about this ticket. We create studies in PB Mock. We don't actually call the back end new_study method. 
When a study is created in PB Mock it is in the PB database, but not in crc_dev database.

When I go to the dashboard, the new study is added to crc_dev database, but I can't figure out how. Is this happening in the front end?

**Comment by w4kpm** [comment]
@cullerton 

As soon as you go and get the crc_workflow endpoint /study - it gets all studies that are new in the PB Mock

It's status is 'new' (or something like it)  -but if you go look at it in the next dashboard, then it's status gets changed to 'in progress', even if you don't do anything at all 

it shouldn't advance the study status until you actually go in and do something with one of the workflows.

**Comment by cullerton** [comment]
@w4kpm 

So, when we go to the dashboard, the front end calls /study. That makes sense now.

And, /study points to api.study.user_studies, which runs StudyService.synch_with_protocol_builder_if_enabled(user)

Thanks, Kelly

**Comment by cullerton** [comment]
@w4kpm 

New studies don't show up in the dashboard. There is no tab for new. Only in_progress, abandoned, hold, and open to enrollment show up.

Where can I see the highlighted row you talk about for new studies?

**Comment by w4kpm** [comment]
That's just it - I saw it sometimes when I was working on the UI stuff, and
not other times, and now that you mention it, yes the studies have to come
back in those pre-defined groupings. I couldn't figure out why it was or
wasn't showing up as 'NEW' - it just did. I wasn't worried about it at the
time because I was just trying to get the graphical elements working, hence
the ticket to get it sorted later.

Why don't you ask Dan& Alex how it *should* work tomorrow in scrum (I won't
make it, and if I do, I'll be really late)

I will propose that it should just show the graphical elements of 'NEW'
(even if the status is in_progress) if there are not task_events ready for
it.  Once someone goes in and starts the first workflow, then it will have
task_events and then the 'In progress' with the progress bar will show up.

If that's the case then we can just assign it back to me and I'll take care
of it, BUT . .

Dan may not like that - he usually rather have stuff 'decided' in the back
end and then the front end keys off of that, in that case I guess come up
with a gameplan w/ Dan and then all 'new' and 'in_progress' status items
would be sent back in the 'in progress' grouping.

my $0.02  - gotta run, but enjoy the normal Thursday meeting.

K

**Comment by cullerton** [comment]
We decided to cancel this ticket.

New study just means the first time a study is moved from Protocol Builder to CR Connect
