### ISSUE TITLE
Group property not with hide_expression

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#19]
If both group and hide_expression properties are specified, the form does not return any shield errors, but it will not load.

I tried this in the Core Info workflow in the Multi-Site task.  I was attempting to use the group property for the last two fields, Q12... and Q14....  The form would not load.  This did not throw a shield error, just would display another task's form.

**Comment by danfunk** [comment]
I thinks this is super out of date, we can definitely use hide_expressions with groups.
