### ISSUE TITLE
Customer Error Messages

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#192]
We want to present users with error messages that are easier to read. Currently, with ApiError, they see the python stack trace. We will allow them to dive down into the python if they want.

**Comment by cullerton** [comment]
Related to 178.

**Comment by cullerton** [comment]
@danfunk 

I'm assigning this to you, for the front end piece.

**Comment by calexh-sar** [comment]
Good start on this, will convert to individual tickets as needed.
