### ISSUE TITLE
Workflow states for Study Dashboard

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#193]
In the Master Workflow, the configurator should be able to specify four states for menu options:

- Required and Ready (active)
- Required and blocked (inactive)
- Optional
- Hidden

These states should be refreshed each time the user is returned to the Study Dashboard, including from the Main Dashboard and from a workflow.    And only required workflows should be counted as part of the overall study progress.

**Comment by w4kpm** [comment]
asterisk for required. 

Also . . . 

Add new message stub to the workflow that will get sent back from the master workflow - then use the message and status to change the display on workflows, and add the message as a tooltip

**Comment by calexh-sar** [comment]
Per Kelly in Slack, the different state types are 'required','disabled','optional','hidden'

**Comment by calexh-sar** [comment]
Working as designed.
