### ISSUE TITLE
Changes to In-Progress Box on Dashboard

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#201]
Currently the InProgress box at the top does nothing with approvals at all 

We discussed this at length in a meeting several days ago, but it looks like the results of that meeting didn't end up in a ticket - 

Part of the reason for this is because we want to get feedback from a sterring committee before we get too crazy with changes, so in the meantime we are going to :

1) make the next tasks /todo box scroll rather than push down the box
2) put both blockers and things I'm blocking in the approvals / Reviews box and make them visually distinct and scroll here as well.

This should be enough for a show & tell and get feedback on that progress.

**Comment by calexh-sar** [comment]
Done
