### ISSUE TITLE
Additional Study Access

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#206]
The user who created a study in Protocol Building will, by default, have full access to that study in CRC2.  Additionally, the Personnel workflow allows for the designation of other users who should have full access to the study as well.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9ab5bc24-7074-4181-9aa1-db99d65a5ffc)

The Main dashboard should present both studies created by the user and any study they have been granted access to in the Personnel workflow of that study.

**Comment by w4kpm** [comment]
- [x] 1) Enable a method to allow script to associate someone with a study
- [x] 1a) add a new table for 1 - study_editors or somesuch = studyid,uvaid,role, perhaps also whether they are allowed access, if they should get emails, etc, etc. This may be useful for showing the people column on the studies list on the dashboard.
- [x] 1b) script is two endpoints - add user to study and remove user to study along with options that directly modifies tables in 1a
      get list, set list of users as *functions* that are accessible from a workflow script task.  
      ** actually this is 4 script functions get_study_associates get_study_associate update_study_associate update_study_associates** 
- [x] 2) change endpoints to also allow a person to pull any study that is associated with them, and not just owned by them
    i.e. /study (the one that returns my studies)
- [x] 3) Make sure that task_events work with this as well -dan was going to do a separate ticket for this
- [x] 4) change get_users_assigned_to_task in  workflow_service @l# 653 to retrieve from list 1a  
- [x] 5) in the workflow service -  we lock tasks that you are not associated with function in 4  - i.e. any endpoint that gives access to modify a study needs to check to make sure that user has access to the study prior to returning the item with an unallowed error if not. 
  **this appears to already be done, which is what Dan said, so I'm marking it done**
- [ ] Add sundry tests for above

**Comment by calexh-sar** [comment]
@w4kpm, I added the _Set Associates_ script task in the Personnel workflow with the following code:

update_study_associate(uid=pi.uid,access=pi.access,send_email=pi.emails,role=pi.label)
update_study_associate(uid=dc.uid,access=dc.access,send_email=dc.emails,role=dc.label)
if cnt_pcs != 0:
  for k in pcs.keys():
    pc = pcs.get(k)
    update_study_associate(uid=pc.uid,access=pc.access,send_email=pc.emails,role=pc.label)
if cnt_aps != 0:
  for k in aps.keys():
    ap = aps.get(k)
    update_study_associate(uid=ap.uid,access=ap.access,send_email=ap.emails,role=ap.label)
if cnt_subs != 0:
  for k in subs.keys():
    sub = subs.get(k)
    update_study_associate(uid=sub.uid,access=sub.access,send_email=sub.emails,role=sub.label)

Associates were set as expected, with the only exception the PI:

  "asscs": [
    {
      "uid": "cah3us",
      "role": "owner",
      "send_email": true,
      "access": true
    },
    {
      "uid": "gfr2f",
      "role": "Department Chair",
      "send_email": false,
      "access": false
    },
    {
      "uid": "eb9tf",
      "role": "Study Coordinator I",
      "send_email": true,
      "access": true
    },
    {
      "uid": "ab8yn",
      "role": "IRB Coordinator",
      "send_email": true,
      "access": true
    },
    {
      "uid": "jcw5b",
      "role": "Additional Study Coordinators",
      "send_email": false,
      "access": false
    },
    {
      "uid": "rrh8z",
      "role": "Department Contact",
      "send_email": false,
      "access": false
    },
    {
      "uid": "gm7sj",
      "role": "Sub Investigator",
      "send_email": false,
      "access": false
    },
    {
      "uid": "jk8t",
      "role": "Sub Investigator",
      "send_email": false,
      "access": false
    },
    {
      "uid": "js7rk",
      "role": "Sub Investigator",
      "send_email": false,
      "access": false
    },
    {
      "uid": "ak2yf",
      "role": "Sub Investigator",
      "send_email": false,
      "access": false
    },
    {
      "uid": "lgs2m",
      "role": "Sub Investigator",
      "send_email": false,
      "access": false
    }
  ],

The PI data is:
  "pi": {
    "label": "Primary Investigator",
    "display": "Always",
    "unique": "Yes",
    "Unnamed: 4": "",
    "Unnamed: 5": "",
    "user_id": "jcw5b",
    "display_name": "Jennifer C Burnsed",
    "affiliation": "faculty, staff",
    "title": "E1:Clinician Physician, E0:Assistant Professor",
    "uid": "jcw5b",
    "telephone_number": null,
    "given_name": "Jennifer",
    "department": "E1:UPG-MD-PEDT Neonatology, E0:MD-PEDT Neonatology",
    "email_address": "jcw5b@virginia.edu",
    "date_cached": "2020-07-02T15:41:08.981000-04:00",
    "sponsor_type": "",
    "E0": {
      "schoolName": "Medicine",
      "deptName": "Pediatrics",
      "specName": "Neonatology"
    },
    "experience": "Jennifer's initial experience plus a bit more. And added this to test ticket #6. And added this to test the Flow sequence script fix. training session fix.",
    "access": true,
    "emails": true
  },

Any assistance with understanding why the PI is not getting set as an Associate would be appreciated.

**Comment by calexh-sar** [comment]
Discussed with Kelly and problem was in the PB API Mock configuration.  The PI's Computing ID was also used for another Personnel and overwriting the PI entry.  Per Kelly's input I am flipping how the associates get set from least important to most important and changing workflow to handle when the PI is also the Dept. Chair.
