### ISSUE TITLE
Automated Email Notifications

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#207]
The Personnel workflow allows for the designation if any of the personnel entered in Protocol Builder should receive automated email notifications. 

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/05306f0f-2ca6-4247-8a8d-e3fb773ad91b)
_Note: This example is from the PI task,  Other roles are asked the same question and should be included as well_

The Configurator needs a efficient way to include all personnel who have been designated to receive automated email notification in the email script task.

**Comment by cullerton** [comment]
When working on this ticket, we should remove the old mails service, and the associated mail templates.

**Comment by cullerton** [comment]
Created [ticket 234](https://app.zenhub.com/workspace/o/sartography/cr-connect/issues/234) to remove the mails service

-- added 03/14
@cullerton,  @danfunk released this ticket today and it does not seem to be working.  Does [ticket 234](https://app.zenhub.com/workspace/o/sartography/cr-connect/issues/234) need to be released as well so make it work?

-- added 03/15
@calexh-sar  No. There is only one branch. The tickets were redundant. We should check this out after scrum

**Comment by cullerton** [comment]
Allow email script to populate the CC field in an email

-- added 03/14
@cullerton, if the ability to add a cc field was released with this ticket, would you please update the wiki to explain how to use it.

-- added 03/15
@calexh-sar Done :)

**Comment by cullerton** [comment]
Lookup for email address should be an LDAP lookup, not user table.

**Comment by calexh-sar** [comment]
Working as designed.
