### ISSUE TITLE
IRB API Mock Study Name

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#209]
The IRB API Mock does not currently handle long study names, such as:

A Phase 1, Open-Label, Dose-Escalation, Safety, Pharmacokinetic, and Pharmacodynamic Study of Oral TP-3654 in Patients with Intermediate-2 or High-Risk Primary or Secondary Myelofibrosis

Allow the Configurator to put in long names for the purpose of accurate display in the Main Dashboard.

Other study names examples can be found here:
[https://app.zenhub.com/files/223421082/13002c6c-3e10-4a59-bbf4-ade37af97279/download](https://app.zenhub.com/files/223421082/13002c6c-3e10-4a59-bbf4-ade37af97279/download)

**Comment by cullerton** [comment]
Currently, the column is varchar(80).

**Comment by calexh-sar** [comment]
Fixed.
