### ISSUE TITLE
Abandon Study

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#21]
One of the four study status sections in the dashboard is Abandoned. The intent for this state is to allow coordinators to place a study in an Abandoned status, which should move it out of the In Progress section and into the Abandoned section when it is known the study will not be completed.

Provide the coordinator with a means to place the study into Abandoned status and take it off Abandoned status and placed back into the In Progress section. It is possible that the study can be placed into a Hold status more that once, although it is highly unlikely that an abandoned study will be reactivated.

Also provide a notes field in that form whose intent is to require the coordinator to record the details regarding a change in state. It should be clear which note goes with which instance of abandoning the study and returning it to the In Progress section/status.

Also assure that the timestamp of where the status was changed is recorded for metrics reporting.

The Abandon workflow was added to the Status category to provide the coordinator with a means to abandon the study. If the coordinator checks the Abandon field and saves, the study should then move to the Abandon section of the dashboard. If they then uncheck it and save, the study should move back to the Active section of the dashboard. Although, it is highly unlikely that an abandoned study will be reactivated.

**Comment by calexh-sar** [comment]
Not working as designed.  The dialog box pops up, allows entry and save.  But study remains where in In Progress.

**Comment by calexh-sar** [comment]
Tested again on 12/22 and not working as designed still.

**Comment by cullerton** [comment]
I believe this issue is fixed, because of ticket 20.

**Comment by calexh-sar** [comment]
Done
