### ISSUE TITLE
Distinguish waiting tasks in 'Approvals' to show which ones I need to take action on and which I'm waiting on

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#210]
Currently all of the tasks in the approvals box are the same weight and color

some are things I am waiting on and some things are things I need to take action on.

Basically if they have my name, I should take action on it - if it is someone elses' name then I am waiting on them to take care of it.

To keep in mind is that this may not be 100% true if we have multiple people that can work on a study.

**Comment by calexh-sar** [comment]
Working as designed.  Going to ask how many someone may have of each type and see if we want to do any sorting as well.
