### ISSUE TITLE
Error when attempting to delete workflow specification

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#217]
When attempting to delete a workflow specification, the empty error dialog pops up:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ddf916c6-0358-4b49-a927-e85e8a3d45af)

This happens if the workflow specifications is empty or not.  If you attempt it again, the workflow specification disappears from the left hand menu, but stays visible in the main panel until the browser is refreshed.  The next available specification should we refreshed in the main panel.

Update on this ticket, just did another delete and the delete worked the first time, but threw the same black error on the screen and this time Sentry was populated with an [InternalError](https://sentry.io/organizations/sartography/issues/2227422043/?project=5260915&referrer=slack) and [IntegrityError](https://sentry.io/organizations/sartography/issues/2098703104/?project=5260915&referrer=slack)

**Comment by cullerton** [comment]
I believe deleting workflow specifications works now. Not sure when this was fixed.

**Comment by calexh-sar** [comment]
Fixed

**Comment by calexh-sar** [comment]
@cullerton this is not working again with the same behavior as before.

First click to delete throws an [Internal Error](https://sentry.io/organizations/sartography/issues/2325132443/?project=5260915&referrer=slack) and [IntegrityError](https://sentry.io/organizations/sartography/issues/2325132414/?project=5260915&referrer=slack).

**Comment by cullerton** [comment]
@calexh-sar I don't get the error, but it doesn't delete the spec for me on testing.
On my laptop however, this **does** work.

Another one to figure out why...

**Comment by cullerton** [comment]
@calexh-sar It looks like this was fixed in the latest push.

**Comment by cullerton** [comment]
@calexh-sar  Never mind.
I see consistent inconsistent behavior.

The first time I try to delete a spec I get the error, and the spec is not deleted.
Try again, and it works. No error. Spec is deleted.

...

**Comment by cullerton** [comment]
We noticed that the url is unchanged after deleting a spec.
I.e., it still has the name of the deleted spec in the url.

We do no think this is the issue, but we should still fix this--probably on the frontend.

**Comment by calexh-sar** [comment]
Working as designed.

**Comment by calexh-sar** [comment]
@cullerton just got this error again when deleting Mike's Test.  Second delete removed it.

**Comment by cullerton** [comment]
I'm not sure why you got the error. 
I just added a spec, then added a bpmn, and then deleted the spec.
The spec was deleted, and I was returned to the master spec

How did you try to delete it?
I clicked on the trash can icon next to the title in the workflow spec box.
(Above ID, Name, Description, and Standalone)

**Comment by calexh-sar** [comment]
Yes, sounds like the same way I deleted it after removing the workflow that was in there:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/07655c2c-2c27-4c23-862a-393266648540)

Here is the [Integrity Error](https://sentry.io/organizations/sartography/issues/2501885356/?project=5260915&referrer=slack) and [Internal Error](https://sentry.io/organizations/sartography/issues/2501885362/?project=5260915&referrer=slack) that was thrown when I get the error.

**Comment by cullerton** [comment]
I snooped around a little, and notice that we delete files from a workflow spec before deleting the spec.
But, sometimes when trying to delete a file, we can't, so we mark it as archived.
I wonder if it is related


except IntegrityError as ie:
    # We can't delete the file or file data, because it is referenced elsewhere,
    # but we can at least mark it as deleted on the table.
    session.rollback()
    file_model = session.query(FileModel).filter_by(id=file_id).first()
    file_model.archived = True
    session.commit()
    app.logger.info("Failed to delete file, so archiving it instead. %i, due to %s" % (file_id, str(ie)))

**Comment by cullerton** [comment]
@calexh-sar Are you still seeing a problem when deleting workflow specs?
I just tried a couple tests on testing and had no issues.
- Created a spec and deleted right away
- Created a spec, reloaded the page and deleted
- Created a spec, added a bpmn file, save the bpmn, returned to configurator home, and deleted the spec

All worked

**Comment by calexh-sar** [comment]
I don't think I have deleted a workflow spec since I got the last errors posted here on July 26.  Since you didn't have any problems in the test you ran, I will close this ticket and we can reopen or write a new one if it occurs again.

**Comment by calexh-sar** [comment]
@cullerton opening this ticket again per our conversation in scrum

**Comment by calexh-sar** [comment]
Received this error when attempting to delete the AppOmni Workflow Specification.  I deleted the three workflows in the Specification first.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/11000e2d-bf54-448a-abb4-936d4b22fefc)

And these Sentry errors were thrown: [PendingRollbackError](https://sentry.io/organizations/sartography/issues/2711011691/?referrer=slack) and [IntegrityError](https://sentry.io/organizations/sartography/issues/2677607951/?referrer=slack).

And as is usually the case, was able to delete the Workflow specification without error on the second attempt.

**Comment by calexh-sar** [comment]
@cullerton I just attempted to delete the Test Workflow Specification from Libraries and got this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/df30ce24-2b06-49e0-ba84-2db64dee2479)
And these Sentry Errors: [PendingRollbackError](https://sentry.io/organizations/sartography/issues/2711011691/?referrer=slack) and [IntegrityError](https://sentry.io/organizations/sartography/issues/2677607951/?referrer=slack).

Prior to getting this error, I was receiving a notification that the Library was still being used by Alex's Tests, even though I had removed the workflow that was calling it and the reference to calling that Library.  I did a hard refresh of the browser, which seemed to clear that notification, but resulted in this error when I attempted to delete the spec.

Also, this time I am not able to delete the Test Workflow Specification on the second attempt as has been the case in the past.  Repeated attempts result in the same errors.

**Comment by calexh-sar** [comment]
I was just able to successfully delete the Test Workflow Specification without error.

**Comment by calexh-sar** [comment]
Not able to delete the Email Attachments and Email Groups Library Workflow Specifications.

**Comment by calexh-sar** [comment]
Not able to delete the LDAP Extract Library Workflow Specification.
