### ISSUE TITLE
Default to Study Short Name after it has been set

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#220]
When a study is first created in Protocol Builder and added to CRC2, the Study Title from PB is displayed.  Once the Study Short Name has been set in the Core Info workflow and the StudyShortName datastore saved, this shorter version should be displayed instead.

**Comment by w4kpm** [comment]
Perhaps better is the following:

Add a short_title to the study database table
allow update using the update_study script that is in place
on the frontend show title if short_title is blank otherwise show short_title 

Alex's reply:
Whatever works best.  Was not trying to be prescriptive on how to do this, just want to be sure you knew that a datastore will be available since it is used in later workflows.

**Comment by w4kpm** [comment]
Make sure this becomes part of study_info

**Comment by w4kpm** [comment]
update_study(title=PIName.abc ,short_title='New Title') would be a way to update the study title.

**Comment by calexh-sar** [comment]
@w4kpm I add the following in the **Save Study Short Name** script task: `update_study(title=StudyShortName)`

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/bdd94b87-13a3-4471-984b-ab86fb35e1a4)

The Enter Study Info user task has the StudyShortName field defined as such:

 ![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9ffb75d4-fe1b-47db-a545-3803c578487b)

The task data after saving the form includes:
  "StudyShortName": "Study of Oral TP",

But when the workflow attempts to execute the **Save Study Short Name** script task, and error is thrown:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/fa61b554-78a4-4bde-b29b-5ddc0613780b)

Any thoughts on what I am doing wrong, and if nothing, what needs to be fixed?

**Comment by w4kpm** [comment]
Are we sure everything has been merged in there?

I’m not seeing anything on crc-errors and the message in the screenshot is
less than helpful

You probably want short_title=ShortTitleName in the script - but title
should work

**Comment by calexh-sar** [comment]
Working as designed.
