### ISSUE TITLE
Master Workflow Status Messages

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#222]
The master workflow is used to determine the status of all other workflows.  It contains only engine tasks (no user tasks), and produces a simple data dictionary. 

[
"workflow_id": "status", 
"workflow_id": "status"
]

for example:
[
{'enter_core_info': 'required'}
]

We need to rework this so that it is possible to provide an explanation of why the status is what it is.   For instance "This workflow is required because you indicated this study involves big harry spiders, and we you need Spider Committee approval for that crazyness!"

I would alter the master workflow to provide a data structure such as:

[
"workflow_id": { status: "status", message: "message" } 
]

And then rework the method _update_status_of_workflow_meta in the Study Service to parse this data, setting both the status and the associated message.

**Comment by calexh-sar** [comment]
Working as designed.
