### ISSUE TITLE
Possible False Positive Shield Test Error in Personnel Workflow

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#224]
Per Meet discussion on 02/26, he following error pops up, but the script seems to run without incident.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8b6107a3-d863-4b33-a428-dd7d5ae48ba0)

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/34ce7ee5-b5e5-4aea-bfff-4f6e283e6de6)

**Comment by cullerton** [comment]
I just ran this locally in debug mode.

When E0_pass_cnt == 2, 
dc is None

It appears that dc is always None, and dc_invalid_uid is False

This is returning None
dc = investigators.get('DEPT_CH', None)

On my machine, investigators does not have DEPT_CH

**Comment by cullerton** [comment]
Alex,

I assigned this back to you. See my comment above.

We can go over this when you get a chance.

Mike

**Comment by calexh-sar** [comment]
Thanks for tracking this down, @cullerton.  I put some guardrails around the dc dict and the error is not happening now.
