### ISSUE TITLE
Change when the master workflow runs

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#227]
Right now, every time a study is requested (including when we get all studies for a person) 
the master workflow gets run on each and every study.

It would be good as a first step to not do this, but only run it when we are requesting one study -such as when we are on the study dashboard and not for the user dashboard 

The result should be that the user dashboard loads in under a second for any arbitrary length of studies for a person

ideally the study dashboard would load in under a second as well.

**Comment by calexh-sar** [comment]
@w4kpm would you please assist me with how to test this or just close the ticket if you can confirm it has been released and working as designed.
