### ISSUE TITLE
Error running workflow_sync/pullall without first running flask clear-db 

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#228]
I tried to run workflow_sync/pullall without first running flask clear-db. (I don't want to lost all my test workflows)

(There are notes for doing this in the README at https://github.com/sartography/cr-connect-workflow)

I got an error back from the api call, because the unique key already existed.

{
  "task_id": "",
  "task_data": "",
  "message": "(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"workflow_spec_category_pkey\"\nDETAIL:  Key (id)=(1) already exists.\n\n[SQL: INSERT INTO workflow_spec_category (name, display_name, display_order) VALUES (%(name)s, %(display_name)s, %(display_order)s) RETURNING workflow_spec_category.id]\n[parameters: {'name': 'approval', 'display_name': 'Approval', 'display_order': 4}]\n(Background on this error at: http://sqlalche.me/e/13/gkpj)",
  "task_name": "",
  "code": "Internal Server Error (500)",
  "file_name": "",
  "task_user": "Unknown"
}

**Comment by calexh-sar** [comment]
@danfunk  will write new ticket for UI.

**Comment by danfunk** [comment]
I believe this is fixed @cullerton ,  can you please verify and then close this ticket if you don't have any issues?

**Comment by cullerton** [comment]
Verified.

- I ran the endpoint from my laptop
- The endpoint returned a list of workflows  
- My Testing workflows are still there
- I can run a workflow
