### ISSUE TITLE
Add field to ApiError attributes.

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#229]
During validation, it would be useful to pass along the form field to ApiError, and display that to the user.

**Comment by cullerton** [comment]
Rather than adding form field as an ApiError attribute, we add it to the actual error message.

While working on this ticket, I found a logic problem with the code for required and hidden. If a field is required but can be hidden, the field must have a default value or a value expression. The code expected *both* a default value and a value_expression. This is fixed now too.

**Comment by calexh-sar** [comment]
Working as designed.
