### ISSUE TITLE
Main Dashboard url

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#230]
Need a url that can be used in emails to take the user to the Main Dashboard page.so they can check the In Progress panel for a task they were just alerted about via email.  This url needs to be instance, i.e., dev, testing, production, etc., aware.

**Comment by calexh-sar** [comment]
@cullerton what is the url?

**Comment by cullerton** [comment]
@calexh-sar 
I guess that would be helpful...

The solution was to create a script that returns the url.

get_dashboard_url()

**Comment by calexh-sar** [comment]
@danfunk or @cullerton please let me know when the fix for the url is available and I will test this ticket.

**Comment by calexh-sar** [comment]
@cullerton (hope your feeling better) I put this code, `main_dash = get_dashboard_url()`, in a script and this was returned in the task data:
```
"main_dash": "https://https://testing.crconnect.uvadcos.io"
```
The extra `https://` keeps it from working.

And correct to assume that once this is fixed `https://testing.crconnect.uvadcos.io' will always redirect to `https://testing.crconnect.uvadcos.io/app/home`?

**Comment by cullerton** [comment]
I believe this is a server config issue.
The environment variable should only be host:port.
The host part should not include https:

Need to check on Mesosphere

**Comment by cullerton** [comment]
@calexh-sar Ready for testing again.

**Comment by calexh-sar** [comment]
Working as designed.
