### ISSUE TITLE
Element Documentation Info Button Tweaks

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#236]
In the [current implementation of the ED Info button](https://github.com/sartography/cr-connect-bpmn/wiki/CR-Connect-Workflow-Configurator---User-Guide#element-documentation-field) tweak the Configurator would enter the text for the info button first and then the line in the ED that will be visible in the header it is associated with second.   A more intuitive implementation would be to reverse these; header line first and then information about what goes in the associated pop-up.

When I chatted with Dan about this in Slack, he replied:

`I agree, it is more intuitive, and it would degrade better.  I am using a float in the CSS to get it on the right, which behaves this way.  But I agree, that it would be better if it came afterwards. In most cases I would expect placing it afterwards to come in a reasonably good position as well, it would just be slightly offset.  There is a lot we could do with the CSS here to position it differently,`

**Comment by NWalker4483** [comment]
This actually is no longer true

**Comment by calexh-sar** [comment]
Fixed by using footnotes approach.
