### ISSUE TITLE
Cant switch to a new user to impersonate if we are already impersonating a user on the frontend

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#237]
The logic on line 65 of user_service.py in cr_connect_workflow appears to disallow switching the impersonate_user if we are already impersonating - it may be as simple as removing the UserService.admin_is_impersonating

but it then breaks something on the frontend - found out that it loads something in the AdminSessionModel table that we needed to clear out first

**Comment by calexh-sar** [comment]
@w4kpm something is still not quite right about this ticket.  I was testing it out and I could change to most everyone on the list except Jeff Pitts.  Sometimes though, there was someone else on the list I could not switch to, but always Jeff Pitts would not work.  I then did a hard refresh, with me selected, so I could try to document exactly what was happening and see if I could find a pattern other than I could not pick the name under my name in the list.  When the screen came back, I no longer had the Admin features to select someone else visible, nor the newly released toggle to hide admin features.  And I was signed in as Jeff Pitts, who I was not able to select before:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ac1160f5-6848-4b61-9ed5-f64b44a01017)

**Comment by calexh-sar** [comment]
Closing this ticket since I have not experienced any similar problems lately.
