### ISSUE TITLE
Remove Scientific Contact from PB Mock Personnel List

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#240]
Since the Scientific Contact is not one of the Personnel Types that can be selected in Protocol Builder...
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/65c47eb3-f3cf-497c-bfb2-d39b0d511828)

...(It is an Auxiliary Information entry based on previously selected personnel:)...
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b5096e6e-67f6-472a-bc4d-6167a329a2b7)

...we should remove it from the PB Mock Investigator Type list:  
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a8d41ab4-0de1-49d2-be33-9eedd3f23e6e)

I also noticed that the Scientific Contact is listed in the investigators.xlsx reference file.  I think this controls some of the PB Mock functionality.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b3a2b86c-3b78-4a8c-970e-298bf965c820)

**Comment by cullerton** [comment]
Removed `Scientific Contact` from the form.

I didn't modify the spreadsheet. The form code doesn't use it.

**Comment by calexh-sar** [comment]
Done
