### ISSUE TITLE
Personnel Workflow False Positive Shield Test

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#242]
The Personnel Workflow is throwing the error shown below which in a discussion with Kelly and Mike was determined to be a false positive caused by `assc` in the code below, which is  evaluating to True in the validation code.

`asscs = get_study_associates()
newPI = False
curPI = ''
newDC = False
curDC = ''
for assc in asscs:
	if assc['role'] == "Primary Investigator":
		 curPI = assc['uid']
	if assc['role'] == "Department Chair":
		 curDC = assc['uid']
del(assc)`

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/2f42ccaa-2036-4bd7-8ce3-d0ae030b0c91)

**Comment by cullerton** [comment]
branch get-study-associates-validation-242

Need to create a workflow to test this.

**Comment by calexh-sar** [comment]
Fixed.
