### ISSUE TITLE
PI name not displaying in Study Dashboard

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#246]
The PI's name is not displaying in the Study Dashboard.  If the PI needs to be added as an Associate first, this may be related to the issue in [Ticket #206.](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/206)

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/235e35cb-fc42-4832-8a9f-f215492797fc)

**Comment by danfunk** [comment]
- [x] Create a new API endooint for listing the personnel associated with a Study (StudyAssociated table)
- [x] Add methods to the SartographyLibraries that allows us to call this endpoint from the frontends
- [x] Use this endpoint to display all the users associated with a study on the main dashboard page.
- [x] REMOVE the primary_investigator_id from Study.  It's bad information, poorly structured, and not correctly populated.

**Comment by calexh-sar** [comment]
@NWalker4483 would you please either point me to where I can find information about the methods to call the new endpoint created display all the users associated with a study.

Also, a reference to the PI remains on the Study page and should be removed per Dan's earlier comment.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/38b13604-ee25-44b5-b455-bdb43eaf6585)

**Comment by NWalker4483** [comment]
@calexh-sar I think the bad information was referring to the``` primary_investigator_id ``` attribute from the ```Study``` angular interface that parts been pulled. The associates endpoint will be with the other study endpoints once it's merged. Its also accessible through the api services```getStudyAssociates(study_id: int) -> List[StudyAssociate]``` method. 

![image.png](https://images.zenhubusercontent.com/600ae36fc5ce0836e9a11e4b/986e7667-8bfa-4a6b-94e2-64f161d39d37)

@danfunk let me know if I misinterpreted your earlier comment

**Comment by calexh-sar** [comment]
@NWalker4483 I just asked for the PI to be displayed, but am getting this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/d95cb507-7777-4033-92ee-5ac45a7d5dfe)

Please removed everyone but the PI

**Comment by calexh-sar** [comment]
Working as designed.
