### ISSUE TITLE
Add New Workflow Spec no longer works.

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#248]
![Screen Shot 2021-03-15 at 12.06.47 PM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/4a475d4d-7373-4a44-8212-990c1d2af3d5)

**Comment by cullerton** [comment]
I see this in the console

ERROR TypeError: t.selectedSpec is undefined

**Comment by calexh-sar** [comment]
Fixed
