### ISSUE TITLE
Cannot create new workflow category

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#249]
I tried to create a new workflow category. 
The ID field is required, but the application doesn't like my input. It keeps saying that the field is required even though something is entered. 
I believe the ID is meant to be something similar to what is auto-generated when creating a new workflow spec.

**Comment by cullerton** [comment]
@calexh-sar 
I just checked. This is still an issue. 
It's probably not a priority since you have the categories set up.
It'll definitely show up though.
Should probably assign back to Dan.

**Comment by cullerton** [comment]
Running through all the backlog.
This is still an issue

**Comment by NWalker4483** [comment]
I agree that id should be generated but I'm not able to reproduce this issue
![image.png](https://images.zenhubusercontent.com/600ae36fc5ce0836e9a11e4b/ee45fe9a-a815-4172-8122-8e754599286f)

**Comment by calexh-sar** [comment]
Working as designed
