### ISSUE TITLE
Revision date should be a date field

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#253]
Perhaps with date validation?

SPONSORS_PROTOCOL_REVISION_DATE in PB Builder Mock

![Screen Shot 2021-03-19 at 8.56.36 AM.png](https://images.zenhubusercontent.com/57a0a334e40e5714b16cd4f1/4b79dc2e-00a8-435a-97e7-abf8e934ca5a)

**Comment by cullerton** [comment]
Done.

It came with a cool date widget for free too.

**Comment by calexh-sar** [comment]
Working as designed.
