### ISSUE TITLE
Jinja Filter length throws false positive shield test error

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#255]
In a manual task's Element Document I included the following code"

`{% if valueIND_1|length > 0 %}`

The shield test threw this error:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/16f96ec8-0b19-4ee9-a836-1005a8019774)

But the code ran without error.

**Comment by cullerton** [comment]
@calexh-sar 
The length filter returns the number of items in a container. 
You can't use it to find the length of a string or number

**Comment by calexh-sar** [comment]
@cullerton if I am understanding this site correctly, it should be able to find the length of a [string](https://jbmoelker.github.io/jinja-compat-tests/filters/length/#string) but not a [number](https://jbmoelker.github.io/jinja-compat-tests/filters/length/#number).

I created a test workflow where I loaded up IND_1 and IND_2 from study_info('details') 
```
details = study_info("details")
ind_1 = details.IND_1
ind_2 = details.IND_2
del(details)
```

and displayed each of them using `value_expression` in a Form Field of Type string.  This passed the shield test with no problem and displayed correctly.  I then added the following in Element Documentation:
```
{{ ind_1|length }}
{{ ind_2|length }}
```
This did not pass the shield test, but display as expected:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/80eef589-31a4-404e-a6a0-4ee88b590413)

I tried removing `{{ ind_1|length }}` since they were all numbers, even though they were being displayed in a string field, but that failed the shied test as well.

**Comment by cullerton** [comment]
@calexh-sar  Here's what I found.

length works with containers (lists, dictionaries)
length works with strings (strings are basically lists)

length does not work with numbers. This produced an error *both* during validation and when running the workflow for me.

This is the expected behavior, since length is really about values in a container. 
https://jinja.palletsprojects.com/en/2.11.x/templates/#builtin-filters

```
 length(obj, /)

    Return the number of items in a container.
```

**Comment by calexh-sar** [comment]
Working as designed.  Tested the following code where `test` is a string form field and it ran successfully and did not return any shield test errors:
```
{{ test }}
{% if test|length >0 %}
{{ test|length }}
{% else %}
No text entered
{% endif %}
```
