### ISSUE TITLE
Allow uploading CSV of Study Details to PB Mock

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#256]
**What**
Allow uploading CSV of Study Details to PB Mock

**Why**
Reduce costly manual input time so that CR Connect support individuals can use PB Mock to troubleshoot and test studies more easily on the testing environment.  

**Use Cases**
Import CSV to a new study with blank study details (or import CSV to update study details on an existing study)

**Notes:**

Export comes from the API endpoint [insert endpoint here, lol]

Here's a link to an example study CSV: https://drive.google.com/file/d/1ygMzKKMG06TjeBDVbHKntUGNJouhlByr/view?usp=sharing

**Comment by calexh-sar** [comment]
Working as designed.
