### ISSUE TITLE
Update/Reorder fields in PB Mock Study Details to match current PB

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#257]
Task 1: Add new fields
Task 2: Confirm ordering is correct

UVA gave us some example studies that included new fields.

Here are just the new/updated fields:

- **IS_SPONSOR_TRACKING** [New]
- **SPONSOR_TRACKING** [New]
- **IS_DSMB** [New]
- **IS_COMPLETE_NON_IRB_REGULATORY** [New]
- **IS_INSIDE_CONTRACT** [New]
- **IS_CODED_RESEARCH** [New]
- **IS_OUTSIDE_SPONSOR** [New]
- **IS_UVA_COLLABANALYSIS** [New]

_Some fields now appear in a slightly different order than before_ (see a side by side comparison on the third tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1lVU3qkk-9Ra1Roj2QCTbavCcBqRvrnX_u9Ar91YWZIU/edit?usp=sharing))

Here's a list of all of the fields together in order. As mentioned above, some fields are new, and are marked below in **bold** and followed by [New]:

IS_IND
IND_1
IND_2
IND_3
IS_UVA_IND
IS_IDE
IDE
IS_UVA_IDE
IS_CHART_REVIEW
IS_RADIATION
GCRC_NUMBER
IS_GCRC
IS_PRC_DSMP
IS_PRC
PRC_NUMBER
IS_IBC
IBC_NUMBER
**IS_SPONSOR_TRACKING** [New]
**SPONSOR_TRACKING** [New]
SPONSORS_PROTOCOL_REVISION_DATE
IS_SPONSOR_MONITORING
**IS_DSMB** [New]
**IS_COMPLETE_NON_IRB_REGULATORY** [New]
IS_AUX
IS_SPONSOR
IS_GRANT
IS_COMMITTEE_CONFLICT
DSMB
DSMB_FREQUENCY
IS_DB
IS_UVA_DB
IS_CENTRAL_REG_DB
IS_CONSENT_WAIVER
IS_HGT
IS_GENE_TRANSFER
IS_TISSUE_BANKING
IS_SURROGATE_CONSENT
IS_ADULT_PARTICIPANT
IS_MINOR_PARTICIPANT
IS_MINOR
IS_BIOMEDICAL
IS_QUALITATIVE
IS_PI_SCHOOL
IS_PRISONERS_POP
IS_PREGNANT_POP
IS_FETUS_POP
IS_MENTAL_IMPAIRMENT_POP
IS_ELDERLY_POP
IS_OTHER_VULNERABLE_POP
OTHER_VULNERABLE_DESC
IS_MULTI_SITE
IS_UVA_LOCATION
NON_UVA_LOCATION
MULTI_SITE_LOCATIONS
IS_OUTSIDE_CONTRACT
IS_UVA_PI_MULTI
IS_NOT_PRC_WAIVER
**IS_INSIDE_CONTRACT** [New]
IS_CANCER_PATIENT
UPLOAD_COMPLETE
IS_FUNDING_SOURCE
**IS_CODED_RESEARCH** [New]
**IS_OUTSIDE_SPONSOR** [New]
IS_PI_INITIATED
IS_ENGAGED_RESEARCH
IS_APPROVED_DEVICE
IS_FINANCIAL_CONFLICT
IS_NOT_CONSENT_WAIVER
IS_FOR_CANCER_CENTER
IS_REVIEW_BY_CENTRAL_IRB
IRBREVIEWERADMIN
**IS_UVA_COLLABANALYSIS** [New]

**Comment by cullerton** [comment]
The form is generated from the DB Model.
Maybe do this as a view, rather than reorder columns

**Comment by cullerton** [comment]
@ajski 
Questions about the new fields.

Are the new fields that start with 'is_' all 0/1 fields?
What type is `sponsor_tracking`?

**Comment by ajski** [comment]
@cullerton 
Yes, all the 'is_' are definitely 0/1 or null

From the example study CSV: https://drive.google.com/file/d/1ygMzKKMG06TjeBDVbHKntUGNJouhlByr/view?usp=sharing. `sponsor_tracking` looks like an integer field

**Comment by cullerton** [comment]
@calexh-sar @ajski 
If y'all can get me hints for the new fields, I'll add them.

**Comment by cullerton** [comment]
We should have all the fields now, in the correct order.

**Comment by ajski** [comment]
Decided to move ahead without the hint text, so as not to hold up this work. (Will make a follow up ticket to add them later once we get clarifying info on the new fields from UVA)

**Comment by cullerton** [comment]
I found another field type issue.
Since we added IS_DSMB, the old DSMB should be changed to a string field.

**Comment by ajski** [comment]
Good catch @cullerton

**Comment by calexh-sar** [comment]
@ajski would you please QA this update and if complete, note as such and close the ticket,  And pls write another ticket to remind us we need to provide the missing hints.

@ajski ^

@ajski ^
