### ISSUE TITLE
PB Mock Study Details make Y/N questions into 0,1,null answers 

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#258]
**STOP** please do some analysis and document findings in issue comments or description if possible. *If this is going to take 1 whole day of work, please throw back to the icebox!* :)

**What**

In PB Mock, Study Details, make Y/N questions into 0,1,null answers. A good general rule of thumb is if the field begins with `IS_` then it should only accept 0, 1, and null. Currently all these fields are integer fields.

And, add validation pls!

**Why**

For anyone in UVA support who is testing CR Connect, we want to make PB Mock as fool proof as possible.

**Comment by cullerton** [comment]
We added integer validation, but did not limit values to 0 and 1.
