### ISSUE TITLE
Deprecate the study_info('protocol') option

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#261]
I added `protocol = study_info('protocol')` to  script task and it threw an error.  Discussed with Dan and he determined that the "protocol" option for that endpoint is no longer needed and should be removed from the code and documentation.

**Comment by calexh-sar** [comment]
@cullerton I don't know how to check the code, but I checked the /list_scripts documentation in Swagger and found:

```
    "name": "StudyInfo",
    "description": "\nStudyInfo [TYPE], where TYPE is one of 'info', 'investigators', 'details', 'documents' or 'protocol'.
```

and at the bottom of the same documentation:

```
### Protocol ###\nReturns information specific to the protocol.
```

**Comment by cullerton** [comment]
@calexh-sar I just committed a fix for this.

**Comment by calexh-sar** [comment]
Did not see any signs of documentation related to the deprecated Protocol endpont.
