### ISSUE TITLE
Optimize Study Dashboard loading

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#263]
The Top Level Workflow for the Study Dashboard does a lot and is slow to load.  Take a look at the workflow and see if anything can be changed to improve loading time.  If not or still slow, check to see if there is anything on how it is getting processed that can help speed it up.

**Comment by w4kpm** [comment]
Removed the workflow metas from the return values in the case of user_studies where we are returning all studies for a user. This took one load (with 17 studies and each of those had in the neighborhood of 40 workflows) from 1.7secs to .2 secs 

unfortunately, we use this to determine how many workflows we need and how many we have to go - AND the number of reviews completed and this breaks the frontend.

**Comment by calexh-sar** [comment]
Closing this ticket since both Kelly and Dan did optimization work.  If any further optimization is needed as we continue to load up the Top Level Workflow we can open a new ticket.
