### ISSUE TITLE
Add last updated date-time and file size to files display in Configurator

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#268]
So the Configurator can be assured their file upload was successful and later check to see when it was last updated, add last updated date-time and file size to files display in Configurator in these two places:

Workflow Specification
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9367c8b7-01f8-4dc1-a882-12f9b4d7e8cc)

Reference Files
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/607a370e-7140-4695-a18d-57a23ed10adf)

**Comment by calexh-sar** [comment]
@NWalker4483 I am seeing the date and time for the Workflow Spec files
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/932ad4e6-ad76-4abb-9c26-19c933176110)

but not the Reference files
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/caaf1652-ca8b-4fcb-89aa-c582ae0a22a8)

**Comment by NWalker4483** [comment]
I think this ticket can be closed

![image.png](https://images.zenhubusercontent.com/600ae36fc5ce0836e9a11e4b/9168357c-b680-45a2-801a-acc19ebb2f87)

**Comment by calexh-sar** [comment]
Working as designed.
