### ISSUE TITLE
Protocol Workflow Script fails shield test, but executes

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#269]
When running the shield test on the Protocol Workflow Specification, the script test in the workflow which has this code:
```
documents = study_info('documents')
isUVA_IRBofRec = not(documents.NonUVAIRB_RelAgreeRequestForm.required)
del(documents)
```
fails and throws [this error](https://sentry.io/organizations/sartography/issues/1841114611/?project=5260915&referrer=slack) and [this error](https://sentry.io/organizations/sartography/issues/2237546321/?project=5260915&referrer=slack):

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ffe11e77-323a-43ff-a425-f3b95564daac)

If I comment out `del(documents)`, I can find:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b50c79ad-aa58-4c37-a972-a6e5eb636d3c)

**Comment by cullerton** [comment]
We couldn't use dot notation in this instance, because documents was just defined.
