### ISSUE TITLE
Protocol Builder Mock Dashboard

### ISSUE THREAD

**Issue by VictoriaSart** [sartography/cr-connect#27]
Interactions- https://www.loom.com/share/b5b748f12fc74ded876b17d8ac6e13aa

- Hovering over requirements items will show the code and name list 
-Hovering over the Investigators items will show the ID and Type
-Clicking on the link under requirements or investigators will take the user to the Protocol Builder Mock Data page to the correct tab for which they clicked  
- Clicking on the vertical dots will show a menu  with (Study Details, Edit Study, Edit Investigators, Edit Documents, Delete Study) 
- The header should contain a help icon (this will have configurator documentation), a profile icon, and a dropdown that allows them to switch between environments (dev, staging, training, prod)

[PB Mock flow.pdf](https://github.com/sartography/cr-connect/files/4624248/PB.Mock.flow.pdf)

**Comment by danfunk** [comment]
Closing as too iced for the icebox.
