### ISSUE TITLE
Check Study IRB API Endpoint in PB Mock

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#273]
We need a way to emulate calling the IRB API [Check Study endpoint](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=CheckStudy&STUDYID=15370) for the active study which returns the key value pairs for `:STATUS"` and `"DETAILS"`.

Example of the data returned for those two keys are:
`{"STATUS":"Error","DETAIL":"Study ID does not exist."}`
`{"STATUS":"Error","DETAIL":"General study errors. UVA Study Tracking Number is missing or not formatted correctly."}`
`{"STATUS":"No Error","DETAIL":"Passed validation."}`

Also need to add this to add this as an option in the PB Mock.  It should replace the _Complete in Protocol Builder?_ checkbox as a dropdown that is  default to: `"STATUS":"No Error","DETAIL":"Passed validation."` when a new study is created.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/d2f65771-e094-443a-b06f-c008f55a9321)

**Comment by cullerton** [comment]
Should be coordinated with [283](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/283)
There are changes in 283 to accomodate removal of Q_COMPLETE column from study table

**Comment by calexh-sar** [comment]
@cullerton would you please provide information on the script task that I would use to  "emulate calling the IRB API Check Study endpoint for the active study which returns the key value pairs for :STATUS" and "DETAILS".

**Comment by cullerton** [comment]
@calexh-sar I don't have a script for you. I missed that functionality.
I will add this to my in_progress and fix it.

**Comment by cullerton** [comment]
Script is check_study. It works for the current study.

**Comment by calexh-sar** [comment]
@cullerton so when this is live would the correct way to use it be:

1. study_status = check_study
1. study_status = check_study()
1. something else

**Comment by cullerton** [comment]
@calexh-sar Numero Two-O

**Comment by calexh-sar** [comment]
Working as designed.
