### ISSUE TITLE
Study Details updated with Review Type data points

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#274]
Jeff G updated the [IRB API Study Details endpoint](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=Study&studyid=15370) on 03/26/21 to include information about the current IRB Review Type.  The PB Mock and testing script need to be updated to reflect this update so we can pull that information into workflows.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/bec4a8fd-8bdc-46a0-a514-32642e36e54c)

**Comment by cullerton** [comment]
@calexh-sar 
Are we adding 2 fields? REVIEW_TYPE and REVIEWTYPENAME? 
Where do they go in the order of fields?

**Comment by calexh-sar** [comment]
@cullerton per the [IRB API Study Details endpoint](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=Study&studyid=15370),  the will be added at the bottom, REVIEW_TYPE will be the next to last and REVIEWTYPENAME the last.

**Comment by calexh-sar** [comment]
Working as designed
