### ISSUE TITLE
Document Pane Updates

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#277]
In a discussion with Dan it was decided that the Document Pane should be updated to show all currently uploaded files.  These files should be segregated by the IRB Categories listed in the irb_documents.xls reference file.  The currently used (where the _Who Uploads? column is not blank or does not have N/A entered in it) Category 1 items are:
- Ancillary Document
- Consent
- Determination Application
- Drug Device Document
- Form
- Grant
- HIPAA
- Non-UVA IRB
- Study
- UVA Compliance
- UVA SIRB
- CR Connect

These Category 1 sections should be collapsible, and show the number of files in each.  If the current workflow involves a file or files to be uploaded/generated, the section or sections where these files can be found should be differentiated.

Within each Category 1 item, the files  should be listed alphabetically as currently shown.  If the current workflow involves a file or files to be uploaded/generated, these files should be differentiated.

**Comment by w4kpm** [comment]
When a file gets uploaded or deleted, the side file pane needs to get updated as well.

**Comment by danfunk** [comment]
I think we should go for something simlar to the following

Admin (3)
  * Adivertisement Checklist 
    * **masdflikj_12.pdf**
  * Continuation Checkist

Drug Device Document
   * FDA Marketing Clearnace ...
       * **> asdlkjasdljdf ... .pdf**

**Comment by calexh-sar** [comment]
Working as designed.
