### ISSUE TITLE
Protocol Builder Mock Data Page

### ISSUE THREAD

**Issue by VictoriaSart** [sartography/cr-connect#28]
-Should contain tabs for: Study Details, Edit Study, Edit Documents, Edit Investigator. 
- Each tab will contain similar data to what it does now with the exception of the edit study tab
-Edit study will have the requirements section move to it's own tab called "Edit Documents" 
-There should also be a back button to take them to the dashboard

[Protocol builder data page.pdf](https://github.com/sartography/cr-connect/files/4624275/Protocol.builder.data.page.pdf)
![Edit investigator annotated](https://user-images.githubusercontent.com/64910981/81857662-904aa000-9530-11ea-8d67-96ab8467e519.png)

**Comment by danfunk** [comment]
all complete.
