### ISSUE TITLE
Remove Sort Arrows from Main Dashboard column headings

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#281]
During a 03/31 post-scrum discussion it was decided that the user did not need to be able to sort the columns on the Main Dashboard since there will be a manageable number of In Progress studies active at any one time.  Kelly had included them in anticipation of adding the sort functionality later.  When someone hovers over the column heading, the arrows should not show up.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/044020a3-2287-4623-8b62-0913e6d1cfc3)

**Comment by w4kpm** [comment]
Unfortunately, the sort arrows were also removed from the 'In Progress' data pane above as well - I'm assuming that we want to keep those??

Please confirm Alex and I'll pop them back in as part of #311 et. al.

**Comment by calexh-sar** [comment]
@w4kpm if "popping them back in" just takes minutes, then yes.  If it will take hours, let's wait until we have a more comprehensive review and discussion on the data pane.

**Comment by calexh-sar** [comment]
Working as designed.
