### ISSUE TITLE
Delete Uploaded Files/Documents Script

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#283]
We need s script that would allow the Configurator to delete a previously uploaded file/document in a Script Task.

**Comment by cullerton** [comment]
Should be coordinated with ticket [273](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/273)
There are changes here to accomodate the removal of Q_COMPLETE column in PB Mock study table

**Comment by calexh-sar** [comment]
Working as designed.
