### ISSUE TITLE
Default value for required custom file/files field with hide_expression

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#289]
Either specify what is an acceptable default value or make exception for these field types.

**Comment by cullerton** [comment]
@calexh-sar 

I think we can close this ticket.

I think you should pick something you are comfortable with--whether that is 'null', 'None', or something else, that configurators should use as the default for this. 

Then we add that to the configurator's guide.

**Comment by calexh-sar** [comment]
Guide updated
