### ISSUE TITLE
Default value for custom type file/files when using hide_expression

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#290]
Provide accepted default value or exempt these two field types from needing a default.

**Comment by cullerton** [comment]
@calexh-sar 

I think we can close this ticket.

I think you should pick something you are comfortable with--whether that is 'null', 'None', or something else, that configurators should use as the default for this. 

Then we add that to the configurator's guide.

**Comment by calexh-sar** [comment]
Updated Configurator's Guide per MIke's comment.
