### ISSUE TITLE
Single checkbox Boolean Property

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#294]
There are several places in CRC1 where single checkboxes are use and prove to be space saving and just as intuitive as boolean radio buttons to the user.  For the Configurator they are problematic due to the need to handle empty lists.  To make the use of a single checkbox more intuitive for the Configurator as well, Dan suggested we  add a Property with  **Id:**_boolean_type_ and **Value:**_checkbox_ to the existing boolean field.

**Comment by Leashys** [comment]
note - do you want an unchecked checkbox to show up in the data model as "whatever: false", or not show up in the data model at all? i(FWIW In formly, an unchecked checkbox will normally not exist in the resulting data model)

**Comment by calexh-sar** [comment]
@Leashys unchecked box should show up as False when the Boolean property is set.

**Comment by Leashys** [comment]
Will have a PR up for this in a minute - for consistency sake, do you also want a possible boolean_type : radio, or just let radio be the default?

**Comment by calexh-sar** [comment]
Per out Slack chat: "just let radio be the default?"

**Comment by calexh-sar** [comment]
@Leashys I kinda remember that there was some philosophical discussion about this, but would like to discuss again the behavior of this field if the Constraint `required` is set to `True`.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/18b03983-2a52-4237-acd3-759648972ce0)

**Comment by Leashys** [comment]
Note to self: We (me) is putting a validator on this, making the form only valid if the checkbox is checked. This is to replace the indeterminate state. It will now only be used in cases like above, where the user must check it

**Comment by calexh-sar** [comment]
Working as designed.
