### ISSUE TITLE
Make the Box conversion work for lists as well

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#296]
Alex ran into a problem with Box where it didn't descend into lists and pick that up.

Make a change so that it descends into both dictionaries and lists

**Comment by calexh-sar** [comment]
@w4kpm would you please assist me with how to test this (or remind me where it was broken and working now) or just close the ticket if you can confirm it has been released and working as designed.

**Comment by w4kpm** [comment]
We have a test in Spiff workflow to make sure that this works. I don't know off the top of my head the exact context of where we ran into this problem. 
 
I will close this based on the merit of the test we added.
