### ISSUE TITLE
Make sure that filename is included in the information that is coming back from the cr-connect-workflow documents script endpoint

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#297]
What is returned should be a dictionary
 
We need the file name included 
category?? 
created and last update times 

( just include all information that is coming back form get-files_for_study line 288 in study_service 

This then would be a FileMeta object on the frontend.
So now we have files as a dict of FileMeta objects - this could just be

**Comment by calexh-sar** [comment]
Working as designed

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/5d93d025-142c-462c-803a-e89750d253e1)
