### ISSUE TITLE
Primary Workflow not set when uploading .bpmn file

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#303]
In ticket #142, the Use Case for setting the Primary Workflow when creating the first .bpmn file in a new Workflow Specification was addressed.  This ticket is for the use case when a new Workflow Specification is created and a bpmn file is uploaded and saved.  If a shied test is run at that time, the No 

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/6c16c955-2785-4619-bba7-f33dc752cc6a)

**Comment by NWalker4483** [comment]
@calexh-sar Is this still an issue on you're end. I've been unable to reproduce the error mentioned

**Comment by calexh-sar** [comment]
@NWalker4483 just tested and working correctly now.
