### ISSUE TITLE
Primary Bpmn not set when uploading .bpmn file

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#304]
In ticket #142, the Use Case for setting the Primary Bpmn when creating the first .bpmn file in a new Workflow Specification was addressed.  This ticket is for the use case when a new Workflow Specification is created and a bpmn file is uploaded and saved.  If a shied test is run at that time, the No Primary BPMN error is thrown.  Similar to Ticket #142, this Use Case should also automatically set the Primary Bpmn file.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/6c16c955-2785-4619-bba7-f33dc752cc6a)

**Comment by cullerton** [comment]
@calexh-sar  Alex, it looks like this is working.

**Comment by calexh-sar** [comment]
Working as designed
