### ISSUE TITLE
Create a script to access the IRB Info data.

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#307]
Follow up to ticket [275](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/275)

We have an api endpoint.

Just need to create a script for workflows.

**Comment by calexh-sar** [comment]
Working as designed

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c39962d4-b29c-40f7-b17e-8fee5dca54ca)
