### ISSUE TITLE
Data Entry Tasks: Last Update gives future date

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#310]
Steps to reproduce:

1. From the Study Dashboard, start a workflow, complete it (or leave it unfinished)
2. Return to the Main Dashboard
3. Toggle to the Data Entry Tab and find the log for your workflow

Expected:
Fairly accurate timestamp

Actual:
"in 3 hours" which is in the future

![Screen Shot 2021-04-26 at 11.07.24 AM.png](https://images.zenhubusercontent.com/57a0a334e40e5714b16cd4f1/e5a5ed1e-46e4-4fc0-90ac-e6b3a62a8314)

**Comment by w4kpm** [comment]
this appears to be a server side issue where the date/time is set for UTC and the laptop / frontend code is running on a  EST time zone.

**Comment by w4kpm** [comment]
After talking to Dan, I need to change the task event to use timezone in the database and possibly also models/workflow.py

Make sure the tz in tranferred to the front end for all date times related to task_events or workflows.

**Comment by calexh-sar** [comment]
@w4kpm, @danfunk released this ticket and while I was confirming tickets this showed up in my In Progress data entry:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/055de240-72de-4f55-9bce-047aa5f87082)

Does frontend work need to be done there to take advantage of your changes or should I put this ticket back into the ZenHub In Progress pipeline so you can take a look at what is going on?

**Comment by w4kpm** [comment]
Put it in in-progress please
