### ISSUE TITLE
Abandoning a study doesn't clear the badges in Data Entry tab

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#311]
Steps to reproduce:

1. Create a study in PB mock
2. From the Study Dashboard, access a couple of the workflows
3. Return to the Main Dashboard, check that you see a row bearing the name of the workflow you accessed in the list under the Data Entry tab, and that the notifications badge number has incremented
4. Move the study to status "Abandoned" through the user interface on Main Dashboard

Expected:
My study is abandoned, I expect the notifications badge number and the table under Data Entry to be cleared of all notifications referencing my old study

Actual:
The notifications and tasks persist (see screenshot)

Note: I initially encountered this because I deleted a study from PB mock (which marks it as "abandoned") and the badge didn't clear.  

![Screen Shot 2021-04-26 at 1.19.54 PM.png](https://images.zenhubusercontent.com/57a0a334e40e5714b16cd4f1/31d672e3-3a84-49cd-8fe7-cf4aab83ef6b)

**Comment by calexh-sar** [comment]
Closing this ticket without testing since the future of the Data Entry tab is uncertain at this time.  Will revisit if we decide to move forward with this feature.
