### ISSUE TITLE
Merge pull request back into knipnap/SpiffWorkflow

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#313]
Work with Kelly as needed to update the Spiff workflow documentation so we can release the latest code to the public.

https://github.com/sartography/SpiffExample/tree/master/docs

Work in this ticket also includes:

- [ ]  Plan for release
- [ ]  Communicate with repository owner
- [ ]  Plan for building community
- [ ]  Major enhancements announcements
- [ ]  Writing a blog about capabilities, with tutorials

**Comment by cullerton** [comment]
I spent some time looking at SpiffWorkflow and SpiffExample documentation.

In general, I believe we are in a good position to move forward.

After we talk with knipknap and decide what to do about the SpiffWorkflow library, I will likely go back and make some changes.

Current ideas revolve around branding and organizing the pieces/parts into a clear structure. I.e., reference, narrative, tutorial.
