### ISSUE TITLE
Improvements to the ability to switch files in Workflow Spec

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#318]
The capability to switch to any file in the Workflow Spec while in the online Camuda Modeler should be updated to include:  
- Switching should invoke the same "notify if unsaved changes" action that clicking the Back button does.
- The currently selected workflow should not be included in to dropdown.

**Comment by cullerton** [comment]
@calexh-sar I just learned from Dan that this is already available.

![Screen Shot 2021-05-28 at 10.13.56 AM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/936ec939-d039-46da-9956-99d764323ec7)

**Comment by calexh-sar** [comment]
@cullerton thx for the info, guess I never checked that option out.  I updated the ticket to include improvements to the current functionality.  The first bullet is a must have, the second is a nice to have and could be moved to a separate ticket and tackled later if preferred.

**Comment by calexh-sar** [comment]
Working as designed.
