### ISSUE TITLE
Add Default option for file_data_get 

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#320]
@Kelly McDonald the User and Study datastores have the default parameter available on the _data_get to set a value if the datastore element does not exist.  The File datastores do not seem to have this option.  Is there a way to check for the existence of a File datastore?  If I use file_data_get for a key value that has not been created yet, it throws this error:

Tuple Index out of range

**Comment by calexh-sar** [comment]
@danfunk has this one been released?

@w4kpm , if so, I used to Swagger to check the file data store for file 1342 and it returned:

```
[
  {
    "last_updated": "2021-07-01T10:21:01.552903-04:00",
    "id": 1391,
    "spec_id": null,
    "study_id": null,
    "user_id": null,
    "value": null,
    "file_id": 1342,
    "workflow_id": null,
    "key": "ShortDesc",
    "task_id": null
  },
  {
    "last_updated": "2021-07-01T10:21:01.552903-04:00",
    "id": 1392,
    "spec_id": null,
    "study_id": null,
    "user_id": null,
    "value": "2021-07-14T04:00:00.000Z",
    "file_id": 1342,
    "workflow_id": null,
    "key": "VerDate",
    "task_id": null
  },
  {
    "last_updated": "2021-07-01T10:21:01.552903-04:00",
    "id": 1393,
    "spec_id": null,
    "study_id": null,
    "user_id": null,
    "value": null,
    "file_id": 1342,
    "workflow_id": null,
    "key": "Lang",
    "task_id": null
  }
]
```
I next added the following code to a script task, ran the shield test successfully and executed it without error:
```
release_test = file_data_get(file_id=1342,key='somekey', default='xyz')
```
After execution, the task data included:
```
"release_test": "xyz"
```
I then reran the Swagger check for the file data store for file 1342 and it was unchanged.  I was expecting to see the key 'somekey' and its  default value 'xyz' added.  Am I missing on this should work.

**Comment by w4kpm** [comment]
Never intended to work this way . . .    

If there is nothing out there, it returns a default - full stop. 

Having it work this way has it's use cases :
if we return a default, it means that no one has updated this yet and in some cases that might be important to know rather than just setting a default without notice.

To get the behavior you are wanting :
release_test = file_data_get(file_id=1342,key='somekey',default=None)
if release_test is None:
    release_test = 'xyz'
    file_data_set(file_id=1342,key='somekey',value=release_test)

I recommend closing this issue and if you really want the file_data_get to update the store if it is returning a default, then we need a new ticket.

**Comment by cullerton** [comment]
I'm running through all the backlog tickets.
Maybe we should discuss this ticket in postscrum and decide what to do.

**Comment by calexh-sar** [comment]
Discussed this with Kelly and now have a better understanding of how the default values for all datastores work.  Closing this ticket, as no work is required.
