### ISSUE TITLE
Markdown macro for expanding an IRB code and displaying files

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#321]
We want a macro that can be embedded in markdown that will:

1) take an IRB document code and find all files for this study that matches the IRB code
2) expands this into a markdown-ready list of links - we may need to mess with how this list gets displayed or rendered.
3) for now, we will just expand it into a bullet list of files 
`
* [file1](downloadlink1)
* [file2](downloadlink2)
`
I don't think we will have any ability to add a hover or any other special effects so we may want to think about any description or meta fields that we want.

**Comment by w4kpm** [comment]
we may also want a list of irb codes - so make sure this is something we can do.

**Comment by calexh-sar** [comment]
@w4kpm is the work on this ticket reflected by the `"url":` entry in each file data dict show below in task data pulled from the application? 

```
    "files": [
      {
        "file_id": 1342,
        "name": "DrugDevicePackageInserts1.docx",
        "url": "/api/file/1342/download?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYWgzdXMifQ.9xkzm3H64rkv0o1y0S---caoxw-4Nx2DM52NBbvONR4",
        "workflow_id": 15082,
        "data_store": {
          "ShortDesc": null,
          "VerDate": "2021-07-14T04:00:00.000Z",
          "Lang": null
        }
      },
      {
        "file_id": 1359,
        "name": "DrugDevicePackageInserts2.docx",
        "url": "/api/file/1359/download?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYWgzdXMifQ.9xkzm3H64rkv0o1y0S---caoxw-4Nx2DM52NBbvONR4",
        "workflow_id": 15082,
        "data_store": {
          "ShortDesc": null,
          "VerDate": "2021-05-11T04:00:00.000Z",
          "Lang": null
        }
      }
    ],
```
