### ISSUE TITLE
Make standalone False by default

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#323]
When creating a workflow spec, we should set standalone to False by default

**Comment by cullerton** [comment]
Made changes in both cr-connect-workflow and cr-connect-bpmn.
Branches are both `standalone-set-default-false-323`

They are literally one-liners.

**Comment by calexh-sar** [comment]
@cullerton when I attempt to create an new Workflow spec, the standalone checkbox looks like this:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a488a526-9551-4c0c-afb8-9894eb0e855c)

I thought that indicates Null and instead it should look like this:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/24f01002-f82a-4a59-8878-ace2895f5cda)

Am I mistaken?

**Comment by cullerton** [comment]
@calexh-sar 
You are not mistaken.

But, I don't think this ticket is pushed to testing yet.

It (the frontend, I believe) puts the dash in there if we don't have a value already. Once you set it, you should see the correct value.

**Comment by calexh-sar** [comment]
@cullerton This is from @danfunk last Friday Slack post:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/e13213e1-cd38-4935-9445-97008d95d7d0)

Are you saying another frontend ticket needs to be written and implemented for this to work, assuming it has been pushed?

**Comment by cullerton** [comment]
@calexh-sar 

I'm saying that it's not working correctly on testing. Dan and I just looked and it appears the code is up there. We are not sure why it isn't working.

Works on my laptop ;)

**Comment by calexh-sar** [comment]
Moving back to In Progress while Mike and Dan figure this out.

**Comment by cullerton** [comment]
@calexh-sar It looks like this is fixed in the latest push.

**Comment by calexh-sar** [comment]
@cullerton when I click on Add new Workflow spec, the standalone checkbox still looks like this:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a488a526-9551-4c0c-afb8-9894eb0e855c)

Is that what we ended up doing, starting with Null?  Or should it look like this:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/24f01002-f82a-4a59-8878-ace2895f5cda)

**Comment by cullerton** [comment]
@calexh-sar 
That is what angular/formly set it to with our settings. 
It as required, and the default is the previous value.

**Comment by cullerton** [comment]
@calexh-sar Maybe Alicia can figure out a way to set it to False if there is no previous value.
That would be cool.

**Comment by calexh-sar** [comment]
@Leashys would you please discuss this ticket with Mike and if you do think you would be able to "figure out a way to set it to False if there is no previous value", assign the ticket to yourself and get with me on priority.  If not, please let me know in here and I will discuss further with Dan and/or Aaron.

**Comment by calexh-sar** [comment]
Alicia replied in Slack that she "basically did the #323 ticket but on DRIVE once before".  Assigning ticket to her and pulling it back into the Backlog so I can prioritize it with her other tickets.

**Comment by calexh-sar** [comment]
Working as designed.
