### ISSUE TITLE
Add Swagger endpoints for File Datastores

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#325]
Similar to user and study datastores, add/update Swagger endpoints to allow for maintenance of file datastore. 

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/82dd217a-f6d7-4bfc-a6a1-e21d68ec5930)

**Comment by cullerton** [comment]
@w4kpm FYI, I'm gonna try to work on this.

**Comment by calexh-sar** [comment]
Working as designed.
