### ISSUE TITLE
Clean up __init__.py in PB Mock

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#328]
The __init__.py file is filling up. Separating the concerns will help delevopment.

- Pull the route methods into a separate file.
- Pull other helper methods into another file.

**Comment by calexh-sar** [comment]
@cullerton don't know of a way I can test this one. Would you pls either provide info on how I can or just close this ticket if you can confirm it has been released and working as designed.

**Comment by cullerton** [comment]
We can close this ticket.
All changes are present.
All tests pass
