### ISSUE TITLE
Study is None in api.workflow.get_task_events

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#329]
Study query returns None for an event in get_task_events.
This caused a 500 error

**Comment by cullerton** [comment]
![Screen Shot 2021-05-14 at 2.05.42 PM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/c952a29a-f022-48cd-83e3-581d27330c24)

**Comment by calexh-sar** [comment]
@cullerton don't know of a way I can test this one.  Would you pls either provide info on how I can or just close this ticket if you can confirm it has been released and working as designed.

**Comment by cullerton** [comment]
We can close this ticket.
Code is in dev branch.
Tests pass.
