### ISSUE TITLE
Data Store Refactor

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#330]
To stay in keeping with the rest of the architecture, it would be good to have a DataStoreService in services, rather than a DataStoreBase in Scripts - I think they would do exactly the same thing, but might help make things a little clearer as to what is used throughout the system, vs what is used by script tasks.

We now call the DataStoreBase from the API and the StudyInfo script, which is adding the data store information onto the files that are returned.

**Comment by cullerton** [comment]
OK to close.
All tests pass.
