### ISSUE TITLE
New 'Is Standalone Workflow' can cause error on entry

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#331]
If you don't select something on the 'is Standalone' question when entering you get the following error

It logs the error but it doesn't display anything on the frontend, it just doesn't add it. 

https://sentry.io/organizations/sartography/issues/2384878386/?project=5260915&referrer=slack

**Comment by cullerton** [comment]
This was fixed in https://github.com/sartography/cr-connect-bpmn/pull/78
We should make sure the code is running on testing.

It works on my laptop running dev branch. 
The save button is grayed out. You can't even create a workflow spec if you don't answer the standalone question.

**Comment by cullerton** [comment]
@w4kpm  I looked, and the new code *is* in the **dev** branch. Are you up to date with BPMN dev branch?
@danfunk  Are we sure dev is running on the testing server?

![Screen Shot 2021-05-28 at 10.26.00 AM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/c2adbe42-6a66-42a6-b986-f9cbefdf3738)

![Screen Shot 2021-05-28 at 10.28.54 AM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/07eb2df0-2979-49ca-9400-ca50a71b92cf)

**Comment by calexh-sar** [comment]
@cullerton or @w4kpm am I correct that the release of ticket #323 fixes this isssue?

**Comment by cullerton** [comment]
Yes

**Comment by cullerton** [comment]
@calexh-sar Yes

**Comment by calexh-sar** [comment]
Fixed by ticket #323
