### ISSUE TITLE
Update PB Mock Documents and Associated Endpoints

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#332]
Jeff Gill recently added additional documents to the [CRConnectAuxDocList](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=CrConnectAuxDocList) IRB API.  Update the PB Mock Documents and associated endpoints so these new documents can be associated with appropriate codes in irb_documents.

The new docs added were:
2	Screening Log
3	Protocol
7	GCRC Approval Form
11	HSR Grant
19	IRB Approval or Letter of Approval from Administration: Send Data or Specimens to UVA
24	InfoSec Approval
33	Data Security Plan
35	Model Consent
39	Age of Majority Cover Letter and Consent
56	Unaffiliated Investigator Agreement
58	FDA Letter granting IND/IDE# or exemption

This list and the complete list of documents can be found here:
[https://app.zenhub.com/files/223421082/fa09a575-2e98-42ab-80a5-34e73ce9f7db/download](https://app.zenhub.com/files/223421082/fa09a575-2e98-42ab-80a5-34e73ce9f7db/download)

**Comment by cullerton** [comment]
@calexh-sar 
The link for the complete list of documents didn't work for me.

**Comment by calexh-sar** [comment]
Works for me, were you on the VPN?

**Comment by cullerton** [comment]
@calexh-sar 

How does this ticket relate to ticket [271](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/271)?

In particular, the Auxiliary Doc List endpoint.  https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=CrConnectAuxDocList

Should our list of documents always match that endpoint?

**Comment by calexh-sar** [comment]
@cullerton #271 was written when those two documents disappeared from our endpoint.  Since then, with the latest update from Jeff G, we are receiving all documents, those two and others.  And yes, PB Mock should reflect all documents returned by the endpoint.

I will close #271.

**Comment by cullerton** [comment]
@calexh-sar 

It looks like this is related to ticket [272](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/272) too

**Comment by calexh-sar** [comment]
Working as designed
