### ISSUE TITLE
Calling a Function in a Script

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#334]
When I tried using this function:
```
def DockLock(isIRBofRec, isLockedUVA, isLockedNonUVA):
	if isIRBofRec and isLockedUVA:
		isDocLock = True
	elif not(isIRBofRec) and isLockedNonUVA:
		isDocLock = True
	else:
		isDocLock = False
	return isDocLock
```
so that this code:
```
isStudy_COIManPlanDocLock = DocLock(isUVA_IRBofRec, sd.locked_if_uva_irb == "🔒", sd.locked_if_non_uva_irb == "🔒")
```
would replace multiple instances of this code:
```
if isUVA_IRBofRec and sd.locked_if_uva_irb == "🔒":
	isStudy_COIManPlanDocLock = True
elif not(isUVA_IRBofRec) and sd.locked_if_non_uva_irb == "🔒":
	isStudy_COIManPlanDocLock = True
else:
	isStudy_COIManPlanDocLock = False
```
in the Load Data Script Task of the study_documents workflow I received a [TypeError: Object of type function is not JSON serializable](https://sentry.io/organizations/sartography/issues/2274753189/?project=5260915&referrer=slack)

**Comment by danfunk** [comment]
When defining even a simple function in a script 
```
def add_one(x):
    return x + 1
a = 1
b = add_one(a)
del(add_one)

```
We encounter a serialization error as it attempts to include add_one as a variable in the task_data moving forward.  Deleting the function (as we do above at the end) is a work around, but not ideal.

Here is the stack trace:
```
 File "/home/dan/.local/share/virtualenvs/cr-connect-workflow-El5Ay3Ak/lib/python3.8/site-packages/SpiffWorkflow/serializer/dict.py", line 843, in <listcomp>
    self.serialize_task(child) for child in task.children]
  File "/home/dan/.local/share/virtualenvs/cr-connect-workflow-El5Ay3Ak/lib/python3.8/site-packages/SpiffWorkflow/bpmn/serializer/BpmnSerializer.py", line 59, in serialize_task
    return super().serialize_task(task,
  File "/home/dan/.local/share/virtualenvs/cr-connect-workflow-El5Ay3Ak/lib/python3.8/site-packages/SpiffWorkflow/serializer/dict.py", line 856, in serialize_task
    s_state['data'] = self.serialize_dict(task.data)
  File "/home/dan/.local/share/virtualenvs/cr-connect-workflow-El5Ay3Ak/lib/python3.8/site-packages/SpiffWorkflow/serializer/dict.py", line 51, in serialize_dict
    return dict(
  File "/home/dan/.local/share/virtualenvs/cr-connect-workflow-El5Ay3Ak/lib/python3.8/site-packages/SpiffWorkflow/serializer/dict.py", line 52, in <genexpr>
    (str(k), b64encode(pickle.dumps(v,
_pickle.PicklingError: Can't pickle <function add_one at 0x7fcd8c875f70>: attribute lookup add_one on __main__ failed
```

**Comment by cullerton** [comment]
This is happening in Python's JSON module.

The encoder is only for data models. 
We might be able to write our own encoder/decoder

> To use a custom ``JSONEncoder`` subclass (e.g. one that overrides the
    ``.default()`` method to serialize additional types), specify it with
    the ``cls`` kwarg; otherwise ``JSONEncoder`` is used.

For now, probably best to use the solution of deleting the function at end of script.

**Comment by cullerton** [comment]
Some more information. We can post scrum tomorrow.


SpiffWorkflow passes serialization to Python in `SpiffWorkflow.serializer.json.dumps`. line 73


`
    return json.dumps(dct, sort_keys=True, default=default)
`

At this point, the script is a string

`type(dct['task_specs']['Activity_RunScript']['script'])`
<class 'str'>

`'# value = tutorial_orig()

def add_two(x):
    return x + 2

value = add_two(3)'`

**Comment by cullerton** [comment]
More info after snooping w/Dan.

`SpiffWorkflow.serializer.json.dumps` line 73 is not the problem.

`SpiffWorkflow.serializer.dict.serialize_task` line 856 is where to look.

**Comment by calexh-sar** [comment]
Able to call methods, have to delete them at the end of the script.  Decision made to run with this.
