### ISSUE TITLE
New method for assigning IRB Codes

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#337]
We have discussed a few things

#1) Currently, we have a REQUIREMENT to have the IRB code on the form ID and this sets the IRB code

#2) we talked about baking the IRB code into the file metadata - so if we have a key of 'irb_code' then it will do something special and update the IRB code on the file so then we can use a variable to set the IRB code 

#3) we talked about the possibility to have a property on the form element something like metadata.language and that will use the language as the key and whatever is in the value property would evaluate and then set the meta data. 
To set the IRB code then we would have metadata.irb_code as the property

**Comment by w4kpm** [comment]
I've added a script where you can set the IRB code using the file metadata and a key of 'irb_code' - but we still need to implement the form property

**Comment by calexh-sar** [comment]
@w4kpm or @danfunk is this basically the backend implementation of the doc_code property?  Should this also be listed in our Scripts documentation so it can be used elsewhere, if needed?
