### ISSUE TITLE
CRConnect is one word

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#338]
WHAT
Please find anywhere we refer to CRConnect within the app itself and make sure to replace `CR Connect` with `CRConnect` An easy place to start is the Main Dashboard, but there may be others to catch with a find/replace.

WHY
The team at UVA confirmed that CRConnect is one word, which is a "must have" for their branding.

![Screen Shot 2021-05-26 at 10.16.22 AM.png](https://images.zenhubusercontent.com/57a0a334e40e5714b16cd4f1/8a22f1d9-b40c-4ee9-8281-494a0354bc38)

**Comment by Leashys** [comment]
@calexh-sar  this one is finally finished for real

**Comment by calexh-sar** [comment]
Working as designed.
