### ISSUE TITLE
update_study_associates() returns error

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#340]
`update_study_associates()` returns "tuple index out of range" and `get_study_associates([])` returns "list index out of range".

Dan looked into it and responded:
This very much looks like a bug in our code on the backend Alex.
`if not len(arg) > 0 and not isinstance(arg[0],dict):`
seems to be invalid logic to me.

Mikes ears perked up.

**Comment by w4kpm** [comment]
Hmm, it looks like that code shouldn't be run unless we are calling update_study_associates

**Comment by calexh-sar** [comment]
Working as designed
