### ISSUE TITLE
Restart a workflow programmatically

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#347]
In cases such as a study getting a new PI, we may need to restart a completed workflow so updates can be made.  Currently, the thought is that this restart will only be called in the Top Level Workflow.

**Comment by cullerton** [comment]
Clarification:

Are we actually starting the workflow and sending the user there, or are we just resetting the workflow so there are no completed tasks?

**Comment by calexh-sar** [comment]
@cullerton we are just restarting the workflow, they will manually navigate to it.

And good question for data and files.  I anticipate that we will not want to clear/delete either, but if not a lot of extra work and we can have those as parameters that default to False if not indicated otherwise, that would be nice.  If significantly more work, leave the parameters out and we can add it later if the need arises.

**Comment by calexh-sar** [comment]
@cullerton would provide or point me to where I can find information about the script to restart a workflow.

**Comment by cullerton** [comment]
@calexh-sar 

Script is reset_workflow
Usage is reset_workflow(workflow_name='blah')

Where blah = the Workflow Specification Name

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/044f3310-10b5-4e8b-b391-4228c4398f52)

Which is `test_example` in the screenshot above.

**Comment by calexh-sar** [comment]
Working as designed.  Will discuss in post scrum about restarting the Top Level Workflow.
