### ISSUE TITLE
Jinja Indent filter not working

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#353]
In the End Event of the pb_api_personnel workflow `{{ pi.experience | indent(4) }}` does not result in an indent.

**Comment by cullerton** [comment]
@calexh-sar 
It turns out this is because the string doesn't have multiple lines. It's just one big long string.
There's no new line to indent.

I'm not sure of a solution yet, but looking deeper into Jinja2 docs.

**Comment by cullerton** [comment]
@calexh-sar I'm thinking we should close this ticket. Yes/No?

**Comment by calexh-sar** [comment]
@cullerton if you were not able to come up with a solution by "looking deeper into Jinja2 docs", or prefer that I do that, then yes.

**Comment by Leashys** [comment]
@calexh-sar One way to address this problem in the bpmn is like so:
In the end event, change the experience section to:

&emsp;**Experience:** 
&emsp;{{pi.experience|replace('\n', '\n&emsp;')}}

This is a pipe that replaces each new-line character with a newline PLUS an indent. The em-indent at the front is needed to indent the first line of the text. 

Let me know if additional information is needed for this

**Comment by calexh-sar** [comment]
@Leashys I tried 
```
&emsp;**Experience:**
&emsp;{{pi.experience|replace('\n', '\n ')}}
```
and got this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/00843472-c361-400a-8cbc-564b3f33b633)

and this `&emsp;**Experience:** {{pi.experience|replace('\n', '\n ')}}` and got this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/eef2480c-8929-475c-8c9e-6e2ef53cfc9d)

Is there something I am missing from your instructions on how to format?

**Comment by Leashys** [comment]
@calexh-sar I thought about it, and the solution I gave yesterday would require the user to put a newline after every line of text. Here is a better alternative:

&emsp;**Experience:** 
&emsp;{{pi.experience|wordwrap(70)| replace('\n', '\n&emsp;')}}

This only allows the formatted lines to be 70 characters long, and puts an indent in front of every new line. So if they do multiple paragraphs, you still get indented blocks. You might want the line length to be more than 70 characters, but I think this achieves what you want :-)

**Comment by calexh-sar** [comment]
@Leashys `{{pi.experience|wordwrap(70)| replace('\n', '\n ')}}`  gave me just about what I was looking forL
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9a549c0d-3897-4e88-a5e7-ac954832e522)

 but I was hoping for the indent to look like this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c1af7cb3-eabd-4d40-837b-25b2bd8e3577)
which I was able to get by adding an additional "indent" after the second `\n`, like this: ``{{pi.experience|wordwrap(70)| replace('\n', '\n  ')}}`
What character is you use for the "indent"?  I tried a space and a tab, but that did not work.  I ended up just do a copy-n-paste of what you had there, but would be nice to know how to get it from scratch.

**Comment by cullerton** [comment]
This may be problematic, since it isn't responsive. Users with wide or narrow devices may have isssues

**Comment by Leashys** [comment]
@calexh-sar the indent character is `&esmp;` (hopefully that shows up and doesn't become an indent). @cullerton is right that this isn't responsive-- if you shorten the screen width, you basically get 70 character paragraphs. I think it is possible to integrate jinja into Angular, but from my understanding crconnect isn't built responsively. (Though it would be nice if it wordwrapped over the length of the angular component)

**Comment by calexh-sar** [comment]
Working as desgned.
