### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by ajski** [sartography/cr-connect#354]
Core story:

SOM CTO requires the ability to access metrics based on **time elapsed** between tasks/events/statuses in CRConnect 2 so that we can identify sticking points in the workflow and address them to continually improve processes.

Basic needs:

- time stamps on tasks/events/statuses

- number of unique users who have started a study

- number of studies started/initiated in CRConnect

^ this last one is pending conversations between the SOM CTO and the UVA IRB to identify at what moment a study should be considered "started" in CRConnect

Examples in this folder:
https://drive.google.com/drive/folders/1NutG-WW7JmwnZl_WfqfdCrYhQq39QXgK?usp=sharing

Example 1: full report Lori gets from CRC1 dashboard
Example 2: how she sorts and abridges it to just what she needs, generated in something called 'Encore'
Example 3: Alex's analysis of full report

**Comment by ajski** [comment]
Outstanding questions to be hammered out:

- How does Lori and team plan to access metrics? Via a Metrics Dashboard, via SQL? Would scheduled auto-generated reports work?

- Do they need reports to run automatically on periodic basis (weekly, monthly)?

- We will probably not support the live monitoring for errors, stuck emails, etc. that Robert added (Lydia mostly uses this) as this was added to CRC1 *after* Sartography work on CRC2 began

**Comment by calexh-sar** [comment]
Notes from 07/06 weekly meeting

- If possible, track the date/time of first time a study was presented to CRC2, even if it does not qualify as a CRC2 study
  - This will be used if it does later qualify as the metric "First created in PB to first qualify as CRC2 study"
  - The "first qualify as CRC2 study" datetime will be used as the equivalent to the "Workflow Creation Date" in the _Lori's Report_ spreadsheet
- Need to track when the first workflow in CRC2 is started.  This will be used as the equivalent to "First Date Workflow Name Created" in the _Lori's Report_ spreadsheet

**Comment by ajski** [comment]
Quick screengrab from the bottom of Lori's Report_5.14.21_abridged which you can also find here: https://drive.google.com/file/d/1lv6kVFpj74XAVGfv6QoKIzc3J_BBAOyj/view

![Screen Shot 2021-07-15 at 4.25.12 PM.png](https://images.zenhubusercontent.com/57a0a334e40e5714b16cd4f1/f7278898-7583-4cf5-88c9-9146632af9be)

It's unclear if this is what Research Leadership asked for specifically in this particular report, or, if this is an indication of ongoing metrics requirements.  

The ZenHub ticket description covers these needs.
