### ISSUE TITLE
One to many PB coversheet docs

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#355]
Currently each PB coversheet document can be assigned to one and only one irb_documents.xlsx  code.  With the recent update of PB coversheet docs, there are cases where one PB coversheet doc needs to be assigned to multiple irb_documents.xlsx  codes, such as:
- Age of Majority Cover Letter and Consent
  - The consent form itself is under Consent/ Age of Majority: Consent_AgeofMajority
  - The Cover letter is under Ancillary Document/ Consent/ Age of Majority Cover Letter: AD_Consent_AgeMajCovLet

Modify the current code so that a single PB coversheet document and be assigned to multiple irb_documents.xlsx  codes, resulting in the data for those documents being set as `.required = True`.

**Comment by cullerton** [comment]
I screwed up and added the code for this ticket to the branch for the [Post Submission States/Events](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/247) ticket.

Waiting on confirmation about whether to create new branch or leave PR the way it is.

**Comment by cullerton** [comment]
This was pushed with the code for [Post Submission States/Events](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/247).
