### ISSUE TITLE
Configurator. push to new environment interaction

### ISSUE THREAD

**Issue by VictoriaSart** [sartography/cr-connect#36]
-Upon hover on any category there will be an upload icon. This gives them they option to push that category and it's workflows to the environment of their choosing 
-The modal will give them a drop down with the different environments (it will not display the one they are currently on), it will highlight the name of the category they are on 
-We need to decide whether we want them to be able to check a box to include all workflow specifications or if we want them to be able to pick from the ones in the category individually... both are represented in the attached image 

Interaction walkthrough: https://www.loom.com/share/c6e2b2d4f03d41cc9fe46e6cf7400902

[push to new env.pdf](https://github.com/sartography/cr-connect/files/4630133/push.to.new.env.pdf)

**Comment by danfunk** [comment]
We have backend endpoints to handle this, but we need to do a pull, not a push.  So this ticket is far off base.  Will be creating a new ticket to cover this.
