### ISSUE TITLE
delete_file() seems to not fully deleted

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#363]
In the Drug/Device workflow I have the following code to check if one or both of the previously required document categories is no longer required and any previously uploaded documents need to be deleted:
```
# Delete Required documents if one or more are not required but were previously required
if not(isPackageInsert) and is_file_uploaded("DrugDevDoc_PackageInsert"):
	delete_file("DrugDevDoc_PackageInsert")
if not(isInvestBrochure) and is_file_uploaded("DrugDevDoc_InvestBrochure"):
	delete_file("DrugDevDoc_InvestBrochure")
```
The steps to reproduce are:
- Initially set both document categories as required in PB Mock
- Run the workflow and add one or more Investigator Brochure documents.  
- Return to PB Mock and unselected Investigator Brochure as a required document
- Restart the workflow and note that Investigator Brochure is not an menu option
- Complete the workflow
- Return to PB Mock and reselected Investigator Brochure as a required document
- Restart the workflow and note that Investigator Brochure is an menu option
- Also note that the "deleted" docs are back,...

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/bdc97167-d49f-4427-bac4-2781502929d3)

but not showing in the Document Pane
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/f61261db-193d-40a0-bba2-3ad0dbb38280)
Attempting to Save these documents throws a blank error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/83bfb36b-7091-4d66-86fd-0002d5184606)
And Sentry captures a [PendingRollbackError](https://sentry.io/organizations/sartography/issues/2475542147/?referrer=slack) and an [IntegrityError](https://sentry.io/organizations/sartography/issues/2475542017/?referrer=slack).

**Comment by danfunk** [comment]
Just some extra details on this -

If you delete a file that was uploaded as a part of a workflow, then you delete that file through some other mechanism (ie not just by returning to the form and deleting it, then submitting the form), then you will get an error when the form, looking at the previously submitted data, tries to load up additional metadata about the file it knows was submitted. 
Clear as mud right?

**Comment by cullerton** [comment]
@calexh-sar 
The new script is delete_task_file_data. 
You pass the task id now, instead of the irb code.

You can pass it with or without they keyword `task_id`.

delete_task_file_data('myTaskId') or 
delete_task_file_data(task_id='myTaskId')

**Comment by cullerton** [comment]
@calexh-sar 

When this ticket is pushed, should we remove the delete_file script? Will it be used anywhere after this change?

**Comment by calexh-sar** [comment]
@cullerton am I understanding correctly that if the delete_file() script were used anywhere, e.g., in the Top Lever Workflow, it would be problematic when returning to the workflow/task where it was originally uploaded?

**Comment by cullerton** [comment]
@calexh-sar That is my belief. We didn't do anything to 'fix' the delete_file script.

**Comment by calexh-sar** [comment]
Then yes, I think we should remove it.

**Comment by cullerton** [comment]
We need to account for cases where multiple doc types could be uploaded in the same task, but we only want to delete one type of doc code.

**Comment by calexh-sar** [comment]
Working as desgned.
