### ISSUE TITLE
Add Date option to Timer Definition Type

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#364]
To finish out the Timer Definition Types, add appropriate code so the Date option is functional.  This should allow the user to specify a date and time when the timer event should occur.

**Comment by w4kpm** [comment]
This already worked.

**Comment by calexh-sar** [comment]
@w4kpm how us the Timer Definition defined for Date?
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/42cf4af0-9769-417d-9597-c7ad52a68dc6)

**Comment by w4kpm** [comment]
Any datetime object will work

datetime.datetime.strptime('2020-10-29','%Y-%m-%d')

or datetime.datetime.now() + timedelta(days=5)

for example

**Comment by calexh-sar** [comment]
I tried using `datetime.datetime.now() + timedelta(days=1)` twice and it did  not work.  Trying `datetime.datetime.strptime('2021-8-14','%Y-%m-%d')` next.

**Comment by calexh-sar** [comment]
datetime.datetime.strptime('2021-8-14','%Y-%m-%d') did not work as well.  Moving this ticket back in In Progress.
