### ISSUE TITLE
Allow a library component to be 'imported' into a normal workflow spec

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#368]
add a new record type to a workflow spec that will import a library component (another workflow spec from a library type) into the current workflow spec.

cr_connect workflow should just import all additional items in the referenced workflow spec into the current workspace. 

This will allow us to reference an external/ shared BPMN or DMN  that lives in the library area from within a workflow spec

**Comment by danfunk** [comment]
I feel like all of this was completed with the library work we did last year.

**Comment by danfunk** [comment]
I feel like all of this was completed with the library work we did last year.
