### ISSUE TITLE
UI Changes to 'import' an external library component 

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#369]
Add something to the modeler tool to be able to import one of our libraries into the current workspace.

this may need to be broken into multiple tickets:

1) add api endpoints to cr_connect_workflow to expose the library groups and the components
2) update the modeler to display these and then add the 'import' record into the current worflow spec. 

This implies that the bpmn has been saved and we already know what workflow spec that BPMN file is in - this option should be disabled if we haven't saved the BPMN and it is already associated with a workflow spec.

**Comment by danfunk** [comment]
I feel like all of this was completed with the library work we did last year.
