### ISSUE TITLE
Restrict Study Load in Main Dashboard based on Review Type

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#374]
The current CRConnect is only used for studies which have the the following IRB Review Types:
- Full Committee
- Expedited
- Non-UVA IRB Full Board
- Non-UVA IRB Expedited

While choosing which studies to load is a manual task in CRC1, it is automated in CRC2.  The work in this ticket is centered around this automation.  Currently CRC2 loads all studies associated with the current user found in PB Mock.  This process should be modified to follow the following rules:
- Check the status of IRB Details IRB REVIEW_TYPE / REVIEWTYPENAME and if the selected combination is... 
  - valid and designated as being in scope for CRC2, load the study.
  - valid and not designated as being in scope for CRC2, do not load the study.
  - not valid, do not load the study.
  - blank, do not load the study.

The full list of Review Type codes and names that could be received from PB is:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8d7a964c-c998-4039-823a-cb43b8fa87d3)

The IRB REVIEW_TYPE and REVIEWTYPENAME variables are currently presented on the Study Details page in PB Mock as string fields:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/24afb4be-44e0-488d-910e-df137668688c)

Modify these fields so they are dropdowns, each loaded with the full list of available review types (ids) and review names.  Additionally, there should be a blank entry in each dropdown.

**Comment by cullerton** [comment]
@calexh-sar 
These are always paired up the same way, right? 
I.e., 1 -> None, 2 -> Full Committee, etc.

If so, I'd like to merge these into 1 pulldown that shows both the id and the string.

1 None
2 Full Committee
3 Expedited
...
26 Non-UVA IRB-Exempt

**Comment by calexh-sar** [comment]
Yes they are @cullerton .  Would I still be able to reference them individually in the code, i.e., In IRB Details, study_info("details"), REVIEW_TYPE and REVIEWTYPENAME?

**Comment by cullerton** [comment]
@calexh-sar 
Yes, I would still store them separately, but this way a configurator couldn't pick an incorrect pair.

**Comment by cullerton** [comment]
@calexh-sar Before doing this, I should ask..

Is that what you mean by 'valid' above? The number and the string match up.

**Comment by cullerton** [comment]
@calexh-sar I decided to move the idea for the single pulldown into a seperate ticket. 
Currenty, the test is on REVIEW_TYPE.
So, if REVIEW_TYPE is 2, 3, 23, or 24 it is valid.

**Comment by calexh-sar** [comment]
Working as designed.
