### ISSUE TITLE
Configurator-Workflow Specification -uploads and additional interactions

### ISSUE THREAD

**Issue by VictoriaSart** [sartography/cr-connect#38]
-Large plus icon should give menu with "Add New" and "Upload Existing" in Link as header text style with no underline #EB5F0C
- Add new takes them to the BPMN CR Connect page to create a new dmn or bpmn diagram(same as now)
-Upload Existing takes them to an upload file modal
-Vertical dots open a menu with the options to "Download", "Edit", "Delete" and if it is an additional bpmn file that is not already the primary bpmn file they will be presented with the option to "Make Primary"
-hovering over the flag will give the user "Primary process" ... this will appear on the bpmn process that has been uploaded first and is the primary process

Interaction: https://www.loom.com/share/b18a6417c06e4c9388e502655aaff508
Full workflow: 
[Configurator flow.pdf](https://github.com/sartography/cr-connect/files/4630197/Configurator.flow.pdf)

**Comment by danfunk** [comment]
too icy for the icebox.
