### ISSUE TITLE
Remove and Prevent `Unnamed' entries in Document Spreadsheet

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#381]
Executing the study_info("documents") script always returns a series of `"Unnamed: nn": "",` entries which are of unknown origin.  Dan has speculated that entries in unused columns of the spreadsheet are the cause, but repeated attempts to assure that all unused columns are empty has not fixed the problem.  Determine the cause, remove these entries and if possible, add code that will either point to the source of the entry so it can be fixed in the spreadsheet or ignore if there is not a column header.

```
  "Unnamed: 15": "",
  "Unnamed: 16": "",
  "Unnamed: 17": "",
  "Unnamed: 18": "",
  "Unnamed: 19": "",
  "Unnamed: 20": "",
  "Unnamed: 21": "",
  "Unnamed: 22": "",
  "Unnamed: 23": "",
  "Unnamed: 24": "",
  "Unnamed: 25": "",
  "Unnamed: 26": "",
```

**Comment by cullerton** [comment]
While destroying the testing database, it seems I 'fixed' this ticket.
We will wait for the problem to occur again so I can troubleshoot.
Icebox for now.

**Comment by danfunk** [comment]
This was corrected in a recent update to the way we manage refernce documents, I now check for null and unnamed fields and remove them when parsing.
