### ISSUE TITLE
Revisit data store service

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#390]
While working on a file data_store issue, we decided to clean up the data store service, so that we have separate methods for file, user, and study.

This way the values passed to the service make more sense, and things are easier to read.
(We won't be passing in a bunch of Nones, needing to keep track of position)
Also, we should probably pass the key and value explicity, not as unnamed *args.

As an example, for file data stores, we only need to pass file_id, key, and value.

**Comment by danfunk** [comment]
This was fixed with yet another recent refactor of the data store.
