### ISSUE TITLE
LDAP Issues - lowercase ids, and better messaging

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#394]
We ran into a problem accessing the LDAP server that caused a waiting task that kept erroring.
It turns out that uppercase IDs fail, so we should lowercase all IDs before accessing the server.
Also, we need to gracefully return to the application when LDAP fails, rather than raising an API Error.

**Comment by cullerton** [comment]
It turns out that upper case UIDs don't fail an LDAP lookup.
Postgres was failing when we tried to add a record to the LDAP table with capitalized UID when a record already existed with lower case UID.
(UVA returns data with UID all lowercase, even when we send a UID with caps.)
We now make sure UIDs are lower case before we work with them.

**Comment by cullerton** [comment]
@calexh-sar For now, the script returns an empty dictionary when we don't get a record from LDAP.
This seems to work with your test script.
We can change that in the future if you need

**Comment by calexh-sar** [comment]
Works for me!  Thx.

**Comment by calexh-sar** [comment]
Working as designed.
