### ISSUE TITLE
Populate DMN table from spreadsheet

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#395]
Filling out a large DMN table can be quite onerous in the current modeler.  Additionally, the source of information for these DMN tables often starts out in a spreadsheet.  For this reason, we should provide the capability to be able to create a DMN table from a spreadsheet.  A proposed template for this process which mirrors the basic layout in the Modeler is attached.  Additional requirements are:
- text values only in the spreadsheet cells, no derived values from formulas
- upload to create a new DMN table only, not update (at this time)
- upload will validate the layout of the spreadsheet is correct, such as...
  - all Input columns are clustered to the left and Output to the right
  - Entry in the..
    - Decision Name
    - Decision ID
    - Input or Output designation for each column
    - Input Label for each column
    - Input Expression for each column
    - Input Type for each column: string, boolean, integer, long, double or date
- all DMN entry validation will be done in the modeler, i.e., not as part of the upload process (this may be added later)

[https://app.zenhub.com/files/223421082/4f120ea6-8a32-4251-8511-06dac5a4b27c/download](https://app.zenhub.com/files/223421082/4f120ea6-8a32-4251-8511-06dac5a4b27c/download)

**Comment by calexh-sar** [comment]
@cullerton per our Slack conversion, this is currently not working.

**Comment by cullerton** [comment]
Looked at this again, and it works correctly. 
Not sure what happened the other day. It may have been human error.

Closing the ticket.
