### ISSUE TITLE
Replace 'libraries' and 'standalone' tags on workflow spec with a single 'workflowspectype' field

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#396]
We will need to change frontend (where you change the types - make that a dropdown)
libraries - to consolidate the fields
cr_connect_workflow - ​/workflow-specification  to allow a user to select only those specific types of workflowspecs

replace /workflow-specification​/standalone and /workflow-specification​/libraries with the previous - and all places that use these endpoints.

**Comment by Leashys** [comment]
I just wrote a ticket #438 that goes hand in hand with this one :)

**Comment by danfunk** [comment]
closed as duplicate of #438
