### ISSUE TITLE
Adding enum_type -> radio to causes error

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#401]
I am working in the Core Info workflow and added the Property enum_type -> radio to an enum field.  When running the workflow that field does not show up.  If I remove that Property, it does show up as a dropdown.  Looking in browser dev tools showed"

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/3227aa96-f3a1-4ed6-af2b-4cc25dd93746)

**Comment by cullerton** [comment]
I replicated this issue locally, and saw this in the browser console.

ERROR TypeError: this.radioGroup._radios is undefined
    getSelected sartography-workflow-lib.js:2799
    RadioDataFieldComponent_Template sartography-workflow-lib.js:2822

**Comment by Leashys** [comment]
note - I believe this was fixed when we updated to Angular 12

**Comment by calexh-sar** [comment]
Working as designed.
