### ISSUE TITLE
A workflow should not be allowed to be both 'standalone' and 'library'

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#409]
Currently, you are allowed to check both 'standalone' and 'library' on a workflow, but these should be mutually exclusive. 

We may want to decide if this should be done only at the cr-connect-bpmn level, or try to have some kind of integrity check at cr-connect-workflow.

**Comment by calexh-sar** [comment]
@w4kpm I am able to check both boxes and click Save.  No error message appears, but it also does not seem to make the changes.  Is this what you implemented?

**Comment by calexh-sar** [comment]
My understanding is this is now covered by Alicia's work to provide a unique process for adding a Library.
