### ISSUE TITLE
Add collapse of the list of libraries on the left hand side of cr-connect-bmpm, and collapse by default

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#411]
We have a list of libraries on the left hand side of cr-connect-bpmn - this allows us to go in and edit any libraries, but this could get long, and we don't want it to clutter up the screen, pushing the regular workflows down too far to be useful.

Add the ability to have this list collapsed by default, and perhaps move it to the bottom of the current workflow categories list.

**Comment by w4kpm** [comment]
Nile, I'll be in here soon for #410 - probably be best to combine tags.

**Comment by calexh-sar** [comment]
Working as designed.
