### ISSUE TITLE
Script Edit Pop-out Width

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#414]
With the recent release, the width of the script edit box decreased.  It should be about twice as wide and if possible, adjustable.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/80972514-93c9-47c7-90f2-bc4b72fbcdc7)

**Comment by cullerton** [comment]
Running through the backlog tickets.
Cannot test because I don't see the popout editor.
