### ISSUE TITLE
Script list dropdown issue

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#415]
The Script list dropdown in the Script editing pop-out is transparent after about 7 entries.  Perhaps it should be opaque the entire way and/or scroll.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/eef924f0-15e0-40f6-8331-b3ce45924c88)

**Comment by cullerton** [comment]
Just doing a review of all backlog tickets.
This is still an issue for me locally.
(I'm not seeing the popout editor at all)
