### ISSUE TITLE
HRS Number on new PB Mock Study Issue

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#417]
If you create a new study in PB mock and add an HSR Number, it moves the Study to Open for Enrollment, instead of In Progress.

The concept of the HSR number has changed since we are going to a single Study Number and we should remove the HSR Number field and any functionality associated with it.

**Comment by cullerton** [comment]
@calexh-sar I am not seeing this behavior. Both on testing, and in local development. 
I created a new study, gave it a `Title`, and entered my `User UVA Computing Id`, and then saved.
Then, I went to Edit Questions, and selected Review Type `2 Full Committee`.

It shows up in `In Progress`.

**Comment by cullerton** [comment]
Looks like it's HSR Number.
If you enter something in HSR Number, it goes to Open Enrollment

**Comment by calexh-sar** [comment]
Fixed
