### ISSUE TITLE
Remove HSR Number field from the add/edit Study page in PB Mock

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#418]

**Comment by cullerton** [comment]
![Screen Shot 2021-08-13 at 9.43.56 AM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/73b87c85-d0f6-4003-8d56-3960b38528db)

**Comment by calexh-sar** [comment]
Working as designed.
