### ISSUE TITLE
Set Sponsor Library workflow throwing error

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#421]
While attempting to run the Study Information workflow which utilizes the Set Sponsor workflow added to the Library, I am getting the error below when running the workflow and choosing options which result in reaching the _Select Entity Name From LDAP_ User Task in Set Sponsor, which are:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/22636de0-687d-4c7a-aa9f-0c6b767803f3)
and result in this error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ab878faf-f739-4b99-9315-3179357330a1)

The Form Field `EntityName` is defined in the _Select Entity Name From LDAP_ User Task:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/cb3480af-7bc3-4440-8b0f-7a466ae73ed6)

The responses from the _Enter Protocol Owner Info_ User Task just before the _Set Protocol Owner_ Call Activity which calls the Set Sponsor workflow is:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/f96b9180-e80e-4377-9c6b-037132337e80)

which returns the following task data:
```
 "EntityType": {
    "value": "UVaPI",
    "label": "UVA Primary Investigator - Investigator Initiated"
```
`"isEntityNameInPB": false,` and `"test": true` where `test = not(isEntityNameInPB) and EntityType.value == "UVaPI"`.

The same error is thrown if the _Select Entity Name From LDAP_ User Task is entered from the alternative flow.  The other flow options leading to the _Enter Entity Text Name_ User Task work as designed.

**Comment by calexh-sar** [comment]
I attempted to add Set Sponsor as as Call Activity in the IND workflow and received the same error:![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/496c1786-74b0-4de2-9cf5-8205e579c926)

**Comment by calexh-sar** [comment]
Closing this ticket since I can no longer recreate after latest release.

**Comment by calexh-sar** [comment]
Was able to recreate issue

**Comment by cullerton** [comment]
Problem is still occuring for me locally.

**Comment by calexh-sar** [comment]
Discussed this problem with Dan yesterday.

**Comment by cullerton** [comment]
@calexh-sar I have difficulty running this workflow in general. 
It may be due to PB Mock settings, or selections I make running the workflow
Whatever the reason, I cannot test this.
Moving to Configuration/QA

**Comment by calexh-sar** [comment]
Working as designed.
