### ISSUE TITLE
Additional IRB Events and Status

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#427]
On the IRB Info page, add the following Events and Status

Add to IRBInfoEvent dropdown:
- 2 - Pending Full Committee Review
- 300 - Approvable with Conditions-New Protocol

Add to IRBInfoStatus dropdown:
- 30 - In PreReview New Protocol

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/aa8cc448-78f9-4d46-b219-d218e1648d0b)

**Comment by cullerton** [comment]
@calexh-sar Add these at the bottom of each list, or is there a specific order you need them?

**Comment by cullerton** [comment]
When we return this info also return the codes in separate fields.

**Comment by cullerton** [comment]
@calexh-sar The 2 new fields are IRBEVENT_ID and IRB_STATUS_ID

**Comment by calexh-sar** [comment]
Working as designed
