### ISSUE TITLE
Configurator Script Task Editor disappeared

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#429]
No longer there when I click on a Script Task.  Seems like there was something else there as well, but don't remember what it was, maybe the minimap icon.  

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/611aa400-246d-4591-afa4-56b1ed86409c)

**Comment by NWalker4483** [comment]
https://github.com/sartography/cr-connect-bpmn/pull/100

**Comment by calexh-sar** [comment]
Fixed.
