### ISSUE TITLE
Email Enhancements

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#430]
Add _reply email_, _bcc_ and _attachments_ options to the current `email()` script.  The _attachments_ option needs to be able to attach a document or documents which were previously uploaded in other workflows to the email.

**Comment by cullerton** [comment]
@calexh-sar How will the documents be identified? By workflow_id and doc_code?

**Comment by calexh-sar** [comment]
@cullerton if needed, we can specify both.  Since all documents of a doc_code type should be attached, will just specifying the code_code work?  Regardless, need to be able to specify multiple doc_codes, and their associated workflow, if needed.

**Comment by cullerton** [comment]
@calexh-sar doc_code by itself won't be enough.
But, the study_id gets passed to a script. So, potentially, I could grab all the workflows for a study, and then get all files uploaded in those workflows that have the doc_code. 
Would this work for you?

**Comment by calexh-sar** [comment]
@cullerton that sounds reasonable

**Comment by calexh-sar** [comment]
Working as designed.
