### ISSUE TITLE
Workflow specificiation menu form requires you to check and uncheck properties

### ISSUE THREAD

**Issue by Leashys** [sartography/cr-connect#433]
In the workflow specification menu, the 'library' and 'standalone' checkboxes must be interacted with in order to validate the form. That is not right. Also it is valid to save the form with both 'library' and 'standalone', but it is not valid, and you end up losing the spec on saving. basically the form within the menu needs a little work

**Comment by calexh-sar** [comment]
@Leashys I just tried filling out the _Add new workflow specification_ form and after adding all the required fields the Save button was not active.  If I am understanding corrrectly that your fix should have done away with the necessity of clicking the Standalone and Library checkboxes, this may need your attemtion.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/5e1da029-09eb-467f-9d91-fc11b1c4080e)

**Comment by calexh-sar** [comment]
Fixed
