### ISSUE TITLE
Workflow Specification Order Position

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#435]
After editing a Workflow Specification's information and saving, the Workflow Specification is placed/moved in the third order position.  It should remain in its original position.

Initially the Test Example Workflow Specification is at the bottom of the list:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/cb80d9a5-54da-40b9-9ac1-d680199d60ff)

When I edited its information and saved:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9ffe9c72-661b-41de-bb01-d889ebf372f6)

It jumps to the third position: 
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/99c452e6-90a3-4493-b06e-7be7ed3381cb)

It should have stayed in its original position.

**Comment by Leashys** [comment]
After working on this with @cullerton , we found this is a more complicated issue. Currently, the BPMN frontend handles the display order re-sorting (in workflow-spec-list component). Every time you edit a workflow, BPMN makes several calls to the backend to try and re-sort the display order. This code should ideally be in the backend entirely. 

This ticket should ideally be 'Remove display_order re-sort code from frontend and add new Api endpoints instead'. more info to come when I think about it more

**Comment by calexh-sar** [comment]
Working as designed.
