### ISSUE TITLE
IND DMN table will not update

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#439]
The IND Check DMN table in the IND Workflow Specification will not open.  When attempting to open, I received these errors:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ebcafb96-52df-4fec-a4e7-d53896612208)

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/655709f8-85ac-4bed-8573-a29fb0d4364c)

I downloaded the file, successfully opened it in the Desktop Camuda Modeler and saved it to my local disk, deleted it from the Workflow Specification and attemped to upload the local file.  Same errors were thrown. 

ZenHub will not allowed the dmn file to be attached to this ticket, so uploading to Slack.

File

**Comment by cullerton** [comment]
I don't think this error comes from the backend.
@danfunk Is it possible this is generated in Angular code?

**Comment by cullerton** [comment]
The latest version of the spec (20191111), requires a <dmndi:DMNDI> section like this.

     <dmndi:DMNDI>
        <dmndi:DMNDiagram>
            <dmndi:DMNShape dmnElementRef="CHANGE_ME_TO_DECISION_ID">
                <dc:Bounds height="80" width="180" x="100" y="100"/>
            </dmndi:DMNShape>
        </dmndi:DMNDiagram>
    </dmndi:DMNDI>
 
You must change the dmnElementRef value to the ID of the <decision> tag. (At the very beginning of the file)

**Comment by calexh-sar** [comment]
Added XML fixed the problem.
