### ISSUE TITLE
hide_expression not evaluating correctly

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#440]
I added the Hide Test workflow to the Test Example Workflow Specification and functions the same way:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/88acc50a-cd7e-4dc8-9c70-ae71a0517a0c)
and
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c849e573-09f2-40ea-a5b6-ca35c301625e)

whether the Test2 Property is set to:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/0941bd67-3082-4b4c-ac28-34e669d4dde6)
or 
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/829108ad-134c-4cc5-8669-62dbe42b8ade)

**Comment by cullerton** [comment]
@calexh-sar This might be because of the parenthesis. I removed them and it seems to be working.
If hide_expression is `Test1`, the field is hidden on Yes, and displayed on No
if hide_expression is `not Test1`, the field is displayed on Yes, and hidden on No

**Comment by calexh-sar** [comment]
Here is what I am seeing:
if hide_expression is not Test1, the field is displayed on Yes, and hidden on No
If hide_expression is changed to Test1 and I click `Start over`, I still see the field is displayed on Yes, and hidden on No.
But if I then do a browser refresh, the field is hidden on Yes, and displayed on No.
And why are the parenthesis no longer working?  I have always used `not(boolean)` and seldom if ever `not boolean` in all other expressions of this type?

**Comment by cullerton** [comment]
@danfunk I'm giving you the expression tickets

**Comment by danfunk** [comment]
I've tested this carefully, and I no longer see this issue.
* Parens are valid, but not required for the NOT operator.  Both work.
* Because this is the first form on the page you aren't getting a refresh of these evaluation functions and they have already been run on these fields,  that's why the browser refresh produces the expected behavior, and a restart does not. We could force a reload of the page on a restart.

**Comment by calexh-sar** [comment]
Working as designed.
