### ISSUE TITLE
Main Dashboard Updates and Fixes

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#441]
WIP

- In Progress section
  - Change the text In Progress to Approvals
  - Remove Approval and Data Entry Tabs
    - Approvals to remain, Data Entry will be depricated
  - Reduce height
    - Auto-expand and/or scroll
    - Collapse to just message if none
- Help Icon 
  - Remove
- Notifications Icon
  - Remove

**Comment by Leashys** [comment]
When you click on your name/user ID on the landing page, there's also a 'profile' and 'notification' page that are "coming soon". Would you like me to remove this menu now too

**Comment by calexh-sar** [comment]
Working as designed.
