### ISSUE TITLE
'Add new workflow specification' Description field should be default hover

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#445]
If a Workflow Specification is not in the Top Level Workflow, it shows up in the Study Dashboard menu as optional.  In these cases, what is entered into Workflow Specification Description field should be displayed as the default hover text.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b88449b6-6a10-4759-8ede-3e24bcd55ca9)

**Comment by cullerton** [comment]
This should probably happen in the DMN file, like all the other messages.

**Comment by calexh-sar** [comment]
Discussed with Mike and agree with his comment above.
