### ISSUE TITLE
Repeating Section List Display issue

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#446]
In the Study Documents workflow _Upload As Applicable Non-UVA IRB Documents_ User Task, the entry for doc_code Pre-Screening Questions looks like this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/82066eb1-d88f-45ad-95b0-9a02ae0aa466)

and the resulting list entry when I first entered that taks looked like this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/cf2b5e8c-dde1-4925-89b4-2e10e96ba1b2)

After doing an edit of the Pre-Screening Questions entry, it looked like this:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/527a2fdd-3f46-4831-9868-b8849e2ecb8d)

It appears to be pulling the two extra fields from the entries for doc_code Survey and Questionnaires:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/f8eab3a2-657f-42c3-8c82-5a0924e20f19)

Additionally, after editing the Pre-Screening Questions, the main Save button was inactive:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/45c54fb0-2cc9-4dcb-85a1-985c9e26a4d3)

**Comment by cullerton** [comment]
I did a quick check of this one, and it seems to be working correctly now. I'm just not completely sure of what the expected behavior is.

**Comment by calexh-sar** [comment]
Confirmed that this seems to be working correctly on testing.
