### ISSUE TITLE
is_file_uplpoaded() issue

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#450]
In the _Protocol, Application & Coversheet_ workfow, `is_file_uploaded()` is returning the error message below istead of a False if the file is not uploaded.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/3fc1e01b-60ea-4c89-85f9-f1053752f261)

**Comment by cullerton** [comment]
I don't think this is happening in is_file_uploaded.
The string in the error message is only found in api.file
 - update_file_data
 - get_file_data
 - get_file_data_link
 - get_file_info

**Comment by calexh-sar** [comment]
@cullerton I removed all scripts but is_file_uploaded() from that flow.  If you haven't already, would you please try to run that workflow in testing locally with this document selected in PB Mock so UVA IRB HSR is not the IRB of record:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c6be4656-5c7f-4673-822f-da7bc6c6721e)

And if you have, I don't have any ideas on how to fix whatever problem I am having.

**Comment by cullerton** [comment]
@calexh-sar First of all, why are you reading this on vacation?
Second, I want to make sure I understand when/where the problem occurs...

We're talking about the script in Activity_0ykr6oi, right?
If I get to UserTask_UploadnonUVACoversheet without seeing the errror, then we are seeing different results?

I can run the workflow on testing--not on my laptop, with or without a file uploaded for UserTask_UploadnonUVACoversheet, and I don't see the error.
The document you posted above (Non UVA...) is the only document selected for my study. No investigators. No sponsors.

If this is still happening for you, can you run it one more time so I can look at the error in Sentry?

**Comment by calexh-sar** [comment]
@cullerton was able to clear the error by using the _Clear documents_ option in _Start over_.    Closing this ticket, as `is_file_uploaded` seems to be working fine now.

**Comment by cullerton** [comment]
To be clear, is_file_uploaded never had a problem. We still don't know what was causing this issue.
