### ISSUE TITLE
Trash can on document entry not working

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#458]
If you incorrectly select the wrong file to upload:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/a6b0e60e-38ed-4b32-9a3f-d7285e52cc74)
And click on the trash can to delete that file immediately, when you select another file to upload and click Save, you get this error.
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/752ada38-0bf0-4990-b69f-a698e82c6f1d)
If you cancel the error, the file you want is there and can be saved, but the trashcan is no longer available;
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/bfab11d4-58b3-4b0a-b2db-a4f52d811b6b)

If initially when you deleted the file using the trash can and then attempt to upload the same file again, it lets you select that file, but does not add it to the form field:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/4d8a8482-4c50-41a0-b1d8-5cfd631c4fd1)
This issue was described in ticket #452, but described here again in case it is useful information.  If two separate issues, it can be address in that ticket.

**Comment by calexh-sar** [comment]
@Leashys I am getting this error now when I remove an incorrect file and pick the correct one, before I click Save.  Also, it will not let me replace with the same file.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/0301239f-0156-4d75-90c8-0aa0088814bc)

**Comment by Leashys** [comment]
@calexh-sar One of my PR's for  this is still at large, I'll get it out this mornin

**Comment by calexh-sar** [comment]
Working as designed.
