### ISSUE TITLE
Template file backups

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#462]
The Template files used to create documents and upload a new DMN table can often involve hours of work by the Configurator to complete fir its specific workflow.  If one is mistakenly deleted from the workflow, we do not have a good way for the Configurator to recover the document and if they cannot access a local copy, the work will need to be done again.  

At the minimum, we should provide the Configurator with a way to recover the latest version.  If not a lot of extra work, being able to recover previous version might be useful as well.

**Comment by danfunk** [comment]
we now store all dmn/bpmn files in GIT with a complete version history.
