### ISSUE TITLE
study_info mislabeled in /list_scripts

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#464]
Seems like it should display `"name": "study_info" instead of:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/adfff9c3-8d73-4bb6-9639-6755fea1c95f)

StudyInfo("info") or any of the other TYPEs does not work.

**Comment by cullerton** [comment]
We decided to add a `handle` entry, that displays the name of the file, which the configurators actually use in a script task.
```
  {
    "name": "StudyInfo",
    "handle": "study_info",
    "description": "study_info(TYPE), where TYPE is one of 'info', 'investigators', 'details', or 'documents'.\n\nAdds details about the current study to the Task Data.  The 
```

**Comment by calexh-sar** [comment]
Working as designed, now seeing:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/3b7277b7-4110-4be9-abfc-ccf98abb4bdb)
