### ISSUE TITLE
Add Scheduled Process that removes unnecessary files 

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#466]
Because of the way the revision history works - we can end up with a lot of unneeded files in the database

Add a scheduled process that looks at any old revisions of a file that are not currently being used by a workflow and deletes them to recover DB file usage. **NEVER** remove a file that is the latest version if a workflow is using it or not.

**Comment by cullerton** [comment]
@w4kpm We're talking about cleaning up the file_data table, right? 
There's 1 entry in the file table, and the different 'revisions' of that file are the multiple entries in the file_data table.

**Comment by w4kpm** [comment]
Yes, the procedure will remove any file_data record that is not the most recent and not currently being used by a workflow.

I did it all in one big SQL statement - do you want to verify?

        -- if a file_data is not the most recent revision
        -- AND file_data is not currently used by a workflow
        -- THEN we delete it. 
        with latest as (
            -- Get the latest revisions
            select 1 as latest,file_model_id, max(version)
            from file_data
            group by 1,2
        ),
        grp as (
            -- Join all latest files in with all file_data records so we can see
            -- which ones are latest and which arent. 
            select coalesce (l.latest, 0) is_latest, fd.id from file_data fd
            left join latest l
            on l.file_model_id = fd.file_model_id
            and l.max = fd.version
            ),
        targeted as (
            -- use the last query and remove any that are currently being used
            select id from grp
            where is_latest = 0
              and id not in (select file_data_id
              from workflow_spec_dependency_file)
        )
        -- delete the final list
        delete from file_data where id in (select id from targeted)

**Comment by cullerton** [comment]
Is that code legal in all 50 states?

It appears to work, but I am now trying to figure out how it works. That is crazy sql. I've never seen anything like that before. Way cool.

**Comment by w4kpm** [comment]
NB - the above query is not quite correct - as it is not excluding anything that is referenced from lookup_file

**Comment by w4kpm** [comment]
Mike I will re-write this query as python using the models / python for maintainability per DAN

**Comment by w4kpm** [comment]
Handed off to Mike to re-factor into python
