### ISSUE TITLE
Add location to do a db sync from a remote location 

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#467]
Just a simple location to be able to use the sync from cr-connect workflow to pull from remote points

* Allow an environment variable to specify the different endpoints
* Get a report back that shows what was pulled from the remote side

Downgrading is not a thing as of this time, if you want to downgrade, you need to zap the DB, do flask db upgrade and then pull from remote.

**Comment by danfunk** [comment]
no longer applicable.
