### ISSUE TITLE
Document link fails

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#476]
Clicking on a document link created in markdown, like: 
```
{%- for f in Protocol_sum.files %}
&emsp;&emsp;**Document Uploaded:** [{{ f.name}}]({{f.url}})
```
which results in:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8dd3a1b3-c420-40cd-9126-f1742c5827df)

fails with this error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/7497e654-361a-4aa2-b827-bc63e84163bb)

**Comment by cullerton** [comment]
@calexh-sar Has this ever worked?

**Comment by calexh-sar** [comment]
I do not remember a time when it worked/

**Comment by cullerton** [comment]
We are only returning the api path part, without the host part

`/file/920/download?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkaGY4ciJ9.ENI4aY3iA_5jOHKr3h_MeSng1-WVGSknHbP6dKZDKDk`

I put in a couple hours on this and could not figure out how to get the correct url.

**Comment by calexh-sar** [comment]
@danfunk assigning you to this ticket as well to see if you can provide some additional direction for Mike.

**Comment by calexh-sar** [comment]
Working as designed.
