### ISSUE TITLE
Libraries not showing as 'selected spec' on page loads

### ISSUE THREAD

**Issue by Leashys** [sartography/cr-connect#477]
If you're on a study spec and reload the page, you will land back on that same study spec. However, if you are on a library and reload the page, you will get a blank screen. This also causes an inability to save any new workflows. When workflow specs are loaded, we are not looping over libraries to see if we should be looking at a library. We also should make the default the master spec, in case the user puts in a bad spec name in the URL, etc.

**Comment by Leashys** [comment]
To add on to this ticket- there are generally just some design issues around workflow specs. Maybe there should be one master running list of all specs, whether they are study, library, master, (potentially standalone), etc. Instead of treating these all separately. will think about it later

Another issue this causes, is that when you add or delete a library, the page doesn't update to reflect this; you have to reload it.

**Comment by calexh-sar** [comment]
Working as designed.
