### ISSUE TITLE
Possible false positive in IDS Approval shield test

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#478]
When I run the shield test on the IDS Approval workflow, I receive this error:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/17e670f8-e3f1-4c8f-b01c-fd28ef368fdf)

Sentry captures this [WorkflowTaskExecException](https://sentry.io/organizations/sartography/issues/2678308692/?referrer=slack) error.

The workflow executes without error and the line of code specified is executed.

**Comment by cullerton** [comment]
This turned out to be a problem with the way we seed data into enum fields during validation.
Checkbox enums are different from enums.
Enums return a dictionary.
Checkbox enums return a list of dictionaries.
We now treat them differently in `get_random_data_for_field`

**Comment by calexh-sar** [comment]
Working as designed.
