### ISSUE TITLE
Issue deleting Library Workflow Specification

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#479]
When attempting to delete the _IDS Email_ Workflow Specification from the Library Category, I receive the following message:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/08d08e82-bfe3-4720-80ad-98be4ceedb55)

I have checked all Workflow Specifications and do not see any that are currently using _IDS Email_.  There were two, _Protocol, Applications & Coversheet" and _IDS Approval_ that were using it.

Work on this ticket includes:
- Determine if there is a remaining reference to the _IDS Email_ Workflow Specification.
- if not, fix so _IDS Email_ Workflow Specification can be deleted

If not a lot of extra effort/time:
- Enhance the message to include the name(s) of the Workflow Specification(s) still using the Library Workflow Specification

**Comment by calexh-sar** [comment]
I did a hard refresh and tried deleting the _IDS Email Workflow Specification_ again and received this error message:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c440909a-c324-4875-8e37-09d3e9be7ea6)

Additionally, the same two Sentry errors discussed in ticket #217 were thrown.

**Comment by cullerton** [comment]
The original error is coming from cr-connect-bpmn.
workflow-spec-list.component.ts line 197.
`if ((wfs.parents.length > 0) && (wfs.library)){`

I thought we were trying to move this type of logic to the back end.
Either way, it looks like wfs.parents has bad data when the check happens.

It's probably better for someone else to look at this.

**Comment by calexh-sar** [comment]
Working as designed.
