### ISSUE TITLE
Remove `name` column from workflow_spec and workflow_spec_category

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#483]
[The name and description for this ticket changed.]

We want to simplify the creation process for workflow_specs and workflow_spec_categories.
We decided to remove the `name` column from both tables, and use the workflow_spec id to identify workflow_specs.

The category id will be hidden from the user.
The spec id will be displayed to the user, and is how the configurator will refer to a workflow_spec.

This is to support ticket [249](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/249) about problems creating workflow categories.

**Comment by calexh-sar** [comment]
#249 is working, but don't know if any way to test that the name column has been removed, so moving to Needs Additional QA
