### ISSUE TITLE
Expose email data

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#487]
For Approvals workflows and likely other Categories, we need to know when emails were sent.  Some emails are only sent once, but many can be resent due to required updates.  In the latter case, the configurator would need to know the date and time for each occurrence.

Work on this ticket includes providing a script that can be used to return the following information about each email sent:
- Subject
- To: email(s)
- From: email(s)
- cc: email(s)
- bcc email(s)
- Date(s) sent

**Comment by cullerton** [comment]
We need a unique identifier for each email, separate from study_id. 
Maybe the Subject can serve as the identifier.
Something like get_email_data(subject='My Email Subject')
(Study_id is already sent with each script call)

**Comment by cullerton** [comment]
It's possible that subjects could be dynamic, which is problematic using them as identifiers.
We could use task id.

**Comment by cullerton** [comment]
My current solution doesn't work for configurators. They won't know the workflow_id. 
Now looking at a combination of workflow_spec_id and study_id.

**Comment by cullerton** [comment]
Bug in validation.
We are looking for element documentation when it doesn't exist.
[Sentry error](https://sentry.io/organizations/sartography/issues/2761889579/?project=5260915&referrer=slack)
