### ISSUE TITLE
API has two different endpoints that do the same thing, but use different authentication methods

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#490]
/workflow-specification/{spec_id}:
  /workflow_sync/{workflow_spec_id}/spec:

Acutally do exactly the same thing api.workflow.get_workflow_specification
BUT I couldn't get multiple authentication methods to work correctly 

Essentially, 

/workflow-specification/{spec_id}:
should respond to both 
    - ApiKeyAuth : [] and   
     - jwt: ['secret']

the second endpoint should be removed, 
the stub should be removed from api/workflow_sync.py (get_sync_workflow_specification) 
the method get_remote_workflow_spec should be updated to use the new API endpoint.  in services/workflow_sync.py

**Comment by w4kpm** [comment]
For what it's worth, this seemed to fail when I tried it on this endpoint, but did work when I tried it on the github endpoints.  - will update this if it works.

**Comment by danfunk** [comment]
Instances no longer talk directly to each other, but through GIT as an intermediary.  So we no longer have multiple authentication methods.
