### ISSUE TITLE
github specific items should have their own call signature

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#491]
I've moved the github specific items to their own section, but the api call is still /file/xxx

For purity sake, you may want to have them be 
/github/xxxx 

There was also talk about having these moved out into some kind of application over view call that got all statuses from the cr_connect_workflow application

If these changes are made:

Change api.yml to reflect the file signature change
change sartography_libraries to reflect the api endpoint change
potentially change cr_connect_bpmn to reflect the new call structure (if the application overview call is created) 

This is currently in the GitSync branch

**Comment by cullerton** [comment]
This ticket is obsolete, with the changes we made moving files to the filesystem and incorporating Git.
