### ISSUE TITLE
Consolidate Group Approvals

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#494]
If an Approval is a group approval, only show one entry in to Approvals section of the Main Dashboard for the Submitter instead of a separate listed to each recipient.  The names of each recipient do not need to be list, just add the word Group to the end of the workflow name.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ccc39366-aa22-4e95-a77e-8828673666f3)

**Comment by cullerton** [comment]
After talking with Dan, we think this should be done in the frontend.
Maybe do an accordian view when it's the same study, task, and workflow, and roll the multiple entries up into one entry.

**Comment by calexh-sar** [comment]
Working as designed.  Received a big shoutout from CRC Team in today's Weekly Meeting for this fix.
