### ISSUE TITLE
Fix workflow spec/category name validation

### ISSUE THREAD

**Issue by Leashys** [sartography/cr-connect#497]
In BPMN, the 'ID' field of a new spec or category can have all kinds of characters that wont save properly in the DB. This field should have its validator updated to only include A-Z, 0-9, and underscores. (Varchar eligible stuff)

**Comment by Leashys** [comment]
Cant start with a number either. go look at this https://forum.camunda.org/t/what-is-a-valid-qname/971 because the spec ID also has to be used as a qName ID in other places

**Comment by calexh-sar** [comment]
Working as designed.

**Comment by calexh-sar** [comment]
Working as designed.
