### ISSUE TITLE
email cleanup

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#498]
Modify the email script so that is returns an email model instead of an email id
Fix the timestamp in the email model
In email_service, raise an error if sending the email fails. Currently, we only log an error.

**Comment by calexh-sar** [comment]
@cullerton, I sent an email at 1:39p and got this in the email data that was returned:

`"timestamp": "2021-10-19T13:39:56.276210-04:00"`

Am I correct that we decided to return UTC and not ET for this value? 

Also, is the best way to test if the email_service raises an error if sending the email fails is to send an email to an invalid email address?  Or is that another type of failure?

**Comment by cullerton** [comment]
@calexh-sar I am storing UTC, but apparently am returning Eastern.
I will move this to in progress.

Also, if I understand your question, those are two different types of errors. The error we are worried about is if the email server has a problem. That is tough to test.

**Comment by cullerton** [comment]
@calexh-sar I'm not seeing this behavior in development. (I get UTC back)
It's like the migration didn't happen on the testing server.
I have a question out to Dan for some clarification.
