### ISSUE TITLE
Convert Time Script

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#499]
Provide a script that will allow the configurator to pass in a Python UTC datetime string and their timezone and it returns a Python local datetime string.

If possible and not more than a few hours of effort, determine how the local user's timezone can be obtained to pass in the script above.  If not, we will default to 'US/Eastern' for now.

**Comment by calexh-sar** [comment]
Per chat with Mike
```
	gmec_email_sent_utc_str = study_data_get("sdsGMEC_email", None)
	gmec_email_sent_utc_dt = dateparser.parse(gmec_email_sent_utc_str)
	gmec_email_sent_localtime = gmec_email_sent_utc_dt.astimezone(pytz.timezone('US/Eastern'))
	gmec_email_sent = gmec_email_sent_localtime.strftime("%m-%d-%Y") + " at " + gmec_email_sent_localtime.strftime("%I:%M %p")
```

**Comment by calexh-sar** [comment]
@cullerton where do I find the documentation on how to use this script?

**Comment by cullerton** [comment]
@calexh-sar I just added something at the bottom of the wiki Script Tasks.
Let me know if you have questions

**Comment by cullerton** [comment]
@calexh-sar I got it down to this.
```
localtime = get_localtime(timestamp=str(datetime.datetime.utcnow()))
fancy = localtime.strftime("%m-%d-%Y")
```

**Comment by cullerton** [comment]
Alex had some issues using the get_localtime script.
It turned out that we didn't return a good enough value from `do_task_validate_only` for the rest of the validation to work.
This was an issue in email, get_email_data, and get_localtime scripts.
We now return the same type of object in `do_task` and `do_task_validate_only`. 
When it makes sense, we actually call do_task.

**Comment by calexh-sar** [comment]
Working as designed with named argument `timestamp=`.  Mike is going to tweak so named argument is optional.

**Comment by calexh-sar** [comment]
@cullerton am I assuming correctly that the Configurator needs to know if the date and time being passed to this script is UTC?  Or maybe asked another way, is there anything script looks for to know if the time is UTC?

**Comment by cullerton** [comment]
The timestamp should include the timezone.

**Comment by calexh-sar** [comment]
Working as designed.
