### ISSUE TITLE
DMN Table not accepting text with line feeds

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#500]
In the Emails Library Workflow specification, I tried having text for the body of an email as our Output which looked like this:
```
"Hello,

This email serves as notification that outstanding documents for IDS have been submitted for the study indicated below.

Please review this submission and work with the Principal Investigator/study team if there are any problems."
```
When I ran the shield test for the IDS Approval workflow, which called that library workflow, I received a [Malformed Output Expression error](https://sentry.io/organizations/sartography/issues/1822760095/?referrer=slack).

If I replaced the text in the DMN table with...
```
"Hello, \n \n This email serves as notification that outstanding documents for IDS have been submitted for the study indicated below. \n \n Please review this submission and work with the Principal Investigator/study team if there are any problems."
```
...no error and the resulting email text is formatted correctly.

Note:  At one time all Element Documentation entries required \n for line feeds.  Code changes we made to inject them instead.

**Comment by cullerton** [comment]
@calexh-sar Dan came up with a great solution for this ticket.
Are you familiar with docstrings in python? They are strings that are wrapped with triple double quotes.

```
"""This is my docstring"""
```

Docstrings can have multiple lines in them. You don't have to worry about escaping quotes

```
"""This is a "quoted" word
And another line

and an extra newline
"""
```

Wrapping the text in the DMN table with triple quotes solves the problem.

**Comment by calexh-sar** [comment]
Very cool that there is a native solution in Python.  Was not familiar with docstrings, but will give them a try and if they work as expected, will close this ticket.

**Comment by calexh-sar** [comment]
Docstrings worked like a charm!
