### ISSUE TITLE
Email Attachments

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#501]
Need the ability to add one or more documents previously uploaded in the study to an email.  Provide ability to attach based on doc_code(s) or file_id(s).

**Comment by cullerton** [comment]
This was done in ticket [430](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/430)
I need to update the wiki

**Comment by calexh-sar** [comment]
Wiki updated.
