### ISSUE TITLE
IDS approval not displaying in the correct order in the Nav

### ISSUE THREAD

**Issue by Leashys** [sartography/cr-connect#502]
Currently, the 'IVRS' task is displaying at the top of the Nav in the IDS approval workflow. The 'Enter IDS Study ID' task should be displayed first. This is happening because there is an additional script task that comes before 'IVRS', but after the exclusive gateway. find out why this script task is given weight when selecting a task in the parallel gateway, and then fix it so it doesnt

**Comment by calexh-sar** [comment]
Working as designed
