### ISSUE TITLE
Tweak Library Category Behavior

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#504]
The All Libraries Category is always collapsed and currently, if you open it to work on a Workflow Specification, it closes when you click the Back -> link.  Very often when I am working in the Category, I need to access multiple Workflow Specifications, and having to reopen the All Libraries Category each time.

Work on this ticket is to keep the Library Category option when the Back -> link is clicked and only close it if another Category is selected.

**Comment by Leashys** [comment]
note to me- I pushed the fix for this onto the 477 - Libraries branch because i needed those changes to fix this. (PR is still out for that)

**Comment by calexh-sar** [comment]
Per Slack discussion with @Leashys, moving back to In Progress so she can fulfill the "close it if another Category is selected" requirement.

**Comment by calexh-sar** [comment]
Working as designed.
