### ISSUE TITLE
required Constraint not work correctly with Enums

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#506]
When the Constraint `required` is set to `True`

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9b9eb61b-d8cc-47e6-ac0b-b9a46064ab4f)

it does not disable the Save button as it has in the past

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b9aacdaa-64b6-4318-9123-fc39e9cf6137)

This appears to be a problem only when `enum_type` is `radio`.

**Comment by Leashys** [comment]
i think this works now with the new enum update. cant replicate

**Comment by calexh-sar** [comment]
Working as designed,
