### ISSUE TITLE
Change behavior if we do on don't have a github repository set up

### ISSUE THREAD

**Issue by w4kpm** [sartography/cr-connect#516]
right now, with the changes for the github sync & changes to the file sync between systems, we are assuming that you *will* have a github repository and that this is the same repository as the remote system.

In some cases we may not want to have a remote github repository - so the behavior should be a  bit different

* never show the sync to github button if we don't have the environment variables set up
* don't impede the file sync from a remote box if we do not have github set up.

**Comment by cullerton** [comment]
With the new Git integration, this ticket can be closed.
