### ISSUE TITLE
hide_expression when enum has not been filled out no longer works

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#518]
An example of this is in the IDS Approval workflow in the Enter Staff Training User Task.  The StaffTrainingDetails text files should be hidden if the StaffTraining enum is blank, i.e., no selection made, or No is selected.  Before the enum refactor, `StaffTraining.value != "No" or StaffTraining.value == None` worked.  Now, `StaffTraining != "No" or StaffTraining == None` does not work.  the `StaffTraining != "No"` part does work, but the `StaffTraining == None` does not.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/6f7e9a09-37e3-4015-998e-acba94338f0c)

**Comment by Leashys** [comment]
This was fixed within some iteration of enum refactors. Documenting that the correct way to do this is `hide_expression` should be set to `StaffTraining == "No" or not StaffTraining` in this specific case. Generally, to use a hide_expression on page load, it should be set to `not Variable`
