### ISSUE TITLE
label_expression not displaying

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#523]
In the _Upload non-UVA Cover Sheet_ User Task of the _Protocol, Application & Cover Sheet_ workflow, the label_expressions for the `NonUVAIRB_StudyProtocolCoversheet` Form Field is not displaying. 

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/4cd35c08-335b-4980-a161-cc1a0d2b8995)

The `lab el_expression` is:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b306d018-aeed-48be-8a9c-eb93e15926c3)

And the task data contains: `"coversheet_label": "🔒 Non UVA IRB Protocol Cover Sheet"`

I tried a couple of things, like removing the `help` Property, but no change.

**Comment by Leashys** [comment]
@calexh-sar i believe this was fixed by something dan did. let me know if this is still an issue for you anywhere :-)

**Comment by calexh-sar** [comment]
@Leashys has the "something dan did" been released yet?

**Comment by Leashys** [comment]
@calexh-sar I believe so? This also seems to be fixed on testing. I believed it was fixed in the enum refactor rollout (in case there's issues in the future)

**Comment by calexh-sar** [comment]
Working as designed.
