### ISSUE TITLE
Save button not disabled when enum field is required and blank

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#526]
The Save button for a Form Field is not disabled if an enum is required has not been selected yet.  An example ofd this is in the IND workflow, where the IND 1 Holder Type is required and has not been selected yet:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/0a5f2200-5724-4609-a518-57ef3b38edec)

but the Save button is enabled:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/f581d4ad-dc56-40b0-88f5-1b58fa371676)

**Comment by Leashys** [comment]
fixed in configuration of the DMN tables @calexh-sar

**Comment by calexh-sar** [comment]
Working as designed with insights from @Leashys
