### ISSUE TITLE
Dates are not retaining value on returning to User Task

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#527]
Dates are not retaining their values if the user returns to a User Task by clicking it in the Nav.  If the date has no value_expression, it returns to null.  If there is a value_expression, it returns to that value.

An example of this can be found in the IBC Approval workflow.  In the _Enter Notification Date_ User Task, the value_expression displays the current date:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9a5df0ef-004c-4980-9fdf-43877bf13528)

If the user changes that date and clicks Save:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/d01f439d-9e68-4c48-9f03-9724fe307ee1)

The Task Data has the new value for the field: `"DateRcvd": "2021-11-04T23:52:55.272458-04:00",`

But if the user selects to return to that task via the Nav, it returns to the default value_expression:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ac2b87f4-3a3d-4e83-a381-9caed9a0bdcd)

Other Form Field types retain the value that was selected and saved.

**Comment by danfunk** [comment]
This says "enums", but it is describing an issue with "Dates"

**Comment by Leashys** [comment]
@danfunk you do it please

**Comment by calexh-sar** [comment]
Working as designed.
