### ISSUE TITLE
Surface additional information in logging scripts

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#529]
We store the task, workflow, study, and a timestamp when logging, but don't return this information to the user when they search the logs.

We should return all this info to the user when they search the logs.

This is related to [ticket 513](https://app.zenhub.com/workspaces/cr-connect-5f0613d95578fa0026063103/issues/sartography/cr-connect/513)

**Comment by cullerton** [comment]
It turns out that we already surface all the information.
I will spend some time turning the scripts into a service, and allowing configurators more options when searching the logs.

**Comment by cullerton** [comment]
Dan turned this into a service when he added code to the front end for displaying logs.
Closing ticket.

**Comment by calexh-sar** [comment]
Closing this ticket, additional information and/or updates to existing will be handled in specific tickets.
