### ISSUE TITLE
Larger font size in markdown_description overlaps Form Field

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#531]
Using the `<font size="3"> text </font>` HTML tag in a markdown_description resulted in an overlap of the Form Field and description area.  Is there anything that can be done to reduce/remove that overlap under this condition?

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/fb044764-d068-44ee-ac5b-b3f591bbf303)

**Comment by Leashys** [comment]
Does the markdown description thing normally look like this? This is how it looks for me on testing

![Screenshot 2021-11-08 at 15-31-37 CRConnect.png](https://images.zenhubusercontent.com/605376307bf33b5036eb360b/06874889-d034-464d-89b8-46705cf660a1)

& is this better? Shouldn't the markdown description be a bit smaller anyways?

![Screenshot 2021-11-08 at 15-31-52 Research Ramp-Up Toolkit.png](https://images.zenhubusercontent.com/605376307bf33b5036eb360b/2aef82df-83a8-4997-b544-39ea27265722)

**Comment by calexh-sar** [comment]
Per our discussion in Meet, keep the markdown_description font as it is now and we can use the tags to make it bigger or smaller as needed.

**Comment by calexh-sar** [comment]
Working as designed.
