### ISSUE TITLE
Dashboard links

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#533]
On the Study Dashboard page
- Removed the _< Back_ link
- Add the hover message "Main Dashboard" for the Rotunda/CRConnect link to the Main Dashboard.
- Shift the Study ID, PI Name and Study Title to the left

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/d531d8ae-adbc-43dd-87f0-49cd013a9837)

On the Study Menu page
- Add the hover message "Main Dashboard" for the Rotunda/CRConnect link to the Main Dashboard.
- Remove the "Return to Study Dashboard" link
- Make the Study number and title a link to the Study Dashboard and add the hover message "Study Dashboard".

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ff4550cf-4c35-4931-850a-ba5ba978864b)

**Comment by Leashys** [comment]
@calexh-sar For the second part, can I keep "Return to study dashboard" if they have not entered a study name (IE the study info has not been filled out yet) ?

**Comment by calexh-sar** [comment]
@Leashys we should always have a study name.  The default if the study short title has not been provided is the study title pulled from PB.

**Comment by calexh-sar** [comment]
@Leashys everything is looking good with one possible exception.  On the Study Menu page, the text _**< Return to Study Dashboard**_ shows up for a second or two and then is replace by the study title.  Is this by design or something that can be fixed so only the study title shows up?

**Comment by Leashys** [comment]
@calexh-sar There's a different approach I can take to mitigate that. Will move this back to in progress and fix it

**Comment by calexh-sar** [comment]
@Leashys with the bounce Dan did just a while ago, looks like we might have regressed on this.![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/36f044b1-1641-4af7-850b-467a8c9194b6)
