### ISSUE TITLE
Transaction Sub-Processes and Cancel Events 

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#546]
When attempting to use a Transaction Sub-Process, the following validation error is thrown:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c5ce0cb3-5321-4d0a-9b1f-e9f43ffb65b7)

The Transaction Sub-Process appear in the Modeler like this:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9446100f-0e1e-420d-955e-2da035e97f23)

and BPMN Spec details on the Transaction Sub-Process can be found [here](https://www.omg.org/spec/BPMN/2.0/PDF#page=208) (Transaction section starts at the bottom of the page).

Other potentially useful articles on this subject include:
-  [Understanding Transactional Subprocesses](https://help.bizagi.com/bpm-suite/en/index.html?understandingtransactionalsubprocesses.htm)

The Cancel Event should be updated to work with the Transaction Sub-Process and no longer work on a User Task.

**Comment by essweine** [comment]
This functionality was added in this PR https://github.com/sartography/SpiffWorkflow/pull/149
