### ISSUE TITLE
Script(s) to get and set Study Status

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#556]
Provide a script or scripts to allow Configurator to get the current Study Status, e.g., _In Progress_, _In Pre-Review_, etc., and set it as it changes during Post Submission.

**Comment by calexh-sar** [comment]
@cullerton when I attempt to run the following code in the study_status.bpmn workflow in Alex's Tests
```
index_cnt = 0
statusStart = get_study_progress_status()
statusCurrent = statusStart
statusList = ['in_progress', 
                'submitted_for_pre_review', 
                'in_pre_review', 
                'returned_from_pre_review', 
                'pre_review_complete', 
                'agenda_date_set', 
                'approved', 
                'approved_with_conditions', 
                'deferred', 
                'disapproved']
max_index_cnt = len(statusList) -1
```
I received the following error message:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/7d9db8f1-037a-4db7-b97f-2ca8c47a46be)
and [WorkflowTaskExecException](https://sentry.io/organizations/sartography/issues/2674702619/?referrer=slack) Sentry error.

Also getting this error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/d4cb0a25-b589-4743-a221-1a5005cd8695)

**Comment by cullerton** [comment]
The files from those code changes are not on the testing server.

```
-rw-r--r-- 1 root root 2054 Dec  9 11:42 get_study_associates.py
-rw-r--r-- 1 root root  706 Dec  9 11:42 get_study_status.py
-rw-r--r-- 1 root root 1498 Dec  9 11:42 get_workflow_status.py
```
