### ISSUE TITLE
Start over Message Event

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#558]
When the _Start over_ button is clicked, we need the option to send notification to the user(s).  This could be done by selectively communicating with a Boundary Message Catch Event, if that Event is attached to the currently active User Task, Manual Task or Sub-Process.  

We should also handle the scenario where a workflow has more than one Boundary Message Catch Event  assigned to a User Task, Manual Task or Sub-Process.  But as stated above, the message should only be sent if one of these is currently active.

**Comment by danfunk** [comment]
Completed
