### ISSUE TITLE
enum_value() not working in Sub-Process

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#559]
When I attempted to use the enum_value() script in a Script Task that was inside a Sub-Process, I received [this error](https://sentry.io/organizations/sartography/issues/2816176243/?referrer=slack).

**Comment by calexh-sar** [comment]
Placing in Icebox for now and we will work with the assumption that the script should be run inside the sub-process.

**Comment by danfunk** [comment]
This is resolved.
