### ISSUE TITLE
Additional Study Statuses

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#562]
Add the following Study Statues so they can be set by the set_study_status() script.

- Submitted for Pre-Review
- In Pre-Review
- Returned from Pre-Review
- Pre-Review Complete
- Agenda Date Set
- Approved
- Approved with Conditions
- Deferred
- Disapproved

None of these should be available as selections on the Main Dashboard page in the Actions for each Study:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/67bf61b2-201b-4603-a780-747eea52be3d)

**Comment by cullerton** [comment]
@calexh-sar These should be displayed on the home page, right?
![Screen Shot Status column.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/e24f4f1d-5461-4b6c-9e9a-b3e57dc20821)

**Comment by cullerton** [comment]
@calexh-sar If a study has one of these new statuses, they should **not** show up on the home page, correct?

**Comment by calexh-sar** [comment]
@cullerton all Statuses should show up in the Status column on the Main Dashboard *home) page.  The ones being added should just not show up in the Actions column as options to manually set.

**Comment by cullerton** [comment]
I was confusing these with Review Type that determines whether we display them :)

Some work will need to be done on the front end to display the new statuses.

**Comment by calexh-sar** [comment]
Implemented as:

    submitted_for_pre_review = 'submitted_for_pre_review'
    in_pre_review = 'in_pre_review'
    returned_from_pre_review = 'returned_from_pre_review'
    pre_review_complete = 'pre_review_complete'
    agenda_date_set = 'agenda_date_set'
    approved = 'approved'
    approved_with_conditions = 'approved_with_conditions'
    deferred = 'deferred'
    disapproved = 'disapproved'

**Comment by calexh-sar** [comment]
set_study_progress_status(), get_study_progress_status(), set_study_status() and get_study_status() working as designed.
