### ISSUE TITLE
Accommodate New Study Statuses in Main Dashbaord

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#564]
Per Mike's comment in ticket #562, update Main Dashboard as needed to accommodate new Study Statuses, which are:

- Submitted for Pre-Review
- In Pre-Review
- Returned from Pre-Review
- Pre-Review Complete
- Agenda Date Set
- Approved
- Approved with Conditions
- Deferred
- Disapproved

**Comment by cullerton** [comment]
From the backend, these are returned all lower case, with underscores. I changed the dashes to underscores too.

```
    submitted_for_pre_review = 'submitted_for_pre_review'
    in_pre_review = 'in_pre_review'
    returned_from_pre_review = 'returned_from_pre_review'
    pre_review_complete = 'pre_review_complete'
    agenda_date_set = 'agenda_date_set'
    approved = 'approved'
    approved_with_conditions = 'approved_with_conditions'
    deferred = 'deferred'
    disapproved = 'disapproved'
```

**Comment by calexh-sar** [comment]
Working as designed.
