### ISSUE TITLE
? inside of quotes should not be evaluated in DMN table

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#588]
Currently a `?` can be used as a variable for numeric evaluation.  The comment in the code is:
```
# NB - the question mark allows us to do a double ended test - for example - our input expr is 5
# and the match expr is 4 < ? < 6  - this should evaluate as 4  < 5 < 6  and it should evaluate as 'True'
```

If a question mark is within quotes, it should be considered as part of that text and not evaluated as part of a numeric expression.

**Comment by cullerton** [comment]
@calexh-sar Where did you get the code comment above?

**Comment by cullerton** [comment]
I found the code comment in SpiffWorkflow.

**Comment by cullerton** [comment]
@danfunk  @calexh-sar 
I can't reproduce this problem, although I may not understand it correctly.
I created a DMN table with a question mark in the input value. It worked, so I don't think it's a good test of this ticket.
Do you have an example where this caused a problem?

**Comment by calexh-sar** [comment]
Can't reproduce
