### ISSUE TITLE
Netbadge update

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#604]
In email received from Cheryl:

Dear Colleague,  

We have identified you as an owner of a software application that uses NetBadge. We are reaching out to inform you of a major NetBadge upgrade that may impact your users’ ability to log in through NetBadge come mid-March. We ask that you test your integration(s) by February 25, 2022, to allow enough time to address any integration issues.  

### **When Is the Update?**
On March 11, 2022, ITS plans to upgrade NetBadge’s core infrastructure from Shibboleth version 3 to version 4 to stay current with the latest code and ensure NetBadge remains as secure as possible. ITS has selected March 11 as a tentative rollout date to reduce the impact of NetBadge downtime during spring break. However, successfully meeting this deadline is dependent on both our internal testing of critical ITS systems and application owners testing across the University. 

### **What We Need From You**
With more than 500 applications relying on NetBadge, ITS needs help from application owners to ensure a smooth upgrade without an inconvenient lapse in service to users. As an application owner, you are responsible for ensuring your software meets the minimum requirements to successfully integrate with NetBadge. Given proper notice, ITS may be able to assist you in meeting the minimum requirements before the upgrade. 

**Complete the following tasks by February 25:**

- Test your software’s compatibility with NetBadge Shibboleth Version 4 using our testing process guide (coming soon).
  - The testing process guide will be posted to ITSWeb by February 10 – check the project page on February 10 for this update).  
- Complete this survey to submit your test results – pass or fail.  
 
If you have any questions, please contact netbadge-v4-upgrade-project@virginia.edu.

**Comment by cullerton** [comment]
I tested cr connect and student testing
Everything went as expected.
I also completed their survey.

**Comment by calexh-sar** [comment]
Closing as complete since we have not heard anything to the contrary.
