### ISSUE TITLE
Workflow end events sometimes return to first User Task

### ISSUE THREAD

**Issue by Leashys** [sartography/cr-connect#615]
If there is nothing in the Element Documentation of the End Event, the workflow will return to the first User Task instead of returning to the study dashboard.  This is a regression, it use to return to the Study Dashboard.

**Comment by Leashys** [comment]
I think this is fixed ETA: it is not

**Comment by calexh-sar** [comment]
@Leashys did you move this back to Backlog because more work is needed after all?

**Comment by Leashys** [comment]
@calexh-sar yes i commented on the wrong ticket! My bad

**Comment by calexh-sar** [comment]
@Leashys the workflow is no longer returning to the first User Task, but it is also not returning to the Study Dashboard if there is nothing in the Element Documentation of the End Event.

**Comment by calexh-sar** [comment]
Fixed
