### ISSUE TITLE
enum_label() error in NICU workflow

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#617]
When running the NICU Committee Approval workflow, I received the following error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/f9c6008e-e23e-4913-8d95-290ce97c13bc)

There is a task with that name in the sub-process in the workflow:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ed9a251d-5056-4f42-af21-cda8ccd41c97)

Similar error in the Data Security Plan workflow:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/1310c971-302c-425f-84b4-7a671ba91742)

**Comment by calexh-sar** [comment]
@cullerton this error is still happing as before after the release and my updates.

**Comment by cullerton** [comment]
It turns out we don't have access to task_specs of a sub process.
We need to make the call to enum_label in the sub process, and then access that variable in task data

**Comment by calexh-sar** [comment]
We are going with the solution that the enum_label() and any other similar scripts must be run in the Sub-Process.
