### ISSUE TITLE
500 Error when running Study Info

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#619]
I am getting this error in the _Select PI Primary Org_ task:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/6f173f35-b3a3-4a81-9895-6889634bbc83)

This workflow was previously completing successfully.

After dismissing the error, the workflow cannot be completed.

**Comment by cullerton** [comment]
I believe this happens during a lookup while building an enum.
If you dismiss the error, nothing is in the pulldown field of the form.

Is it possible for this to be a timing issue?
Something is taking too long, and we don't have the filename in our hand when we need it?

In the debugger, PyCharm jumps around without me clicking the continue button.

**Comment by calexh-sar** [comment]
Passing to Dan to see if it is performance related.

**Comment by calexh-sar** [comment]
Still a bit slow, but not failing
