### ISSUE TITLE
Initial cursor focus to OK in Help dialog modals

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#62]
When displaying a help modal, cursor focus should aways go the the Ok button initially.  Currently, if there is linked text, it goes there instead.

**Comment by calexh-sar** [comment]
This is not working, initial focus is still on any clickable text in the body of the dialog box.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/fdf08579-4c95-48b0-8373-25e5b0a9a340)

**Comment by calexh-sar** [comment]
@NWalker4483 I am still seeing the same behavior of focus on the first possible selection and not the OK button:

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/99f0a323-6b7a-48b7-af98-776d470e6f98)

**Comment by NWalker4483** [comment]
I don't think that code has been merged yet, I'll check it out rn.

**Comment by NWalker4483** [comment]
Checked and its working on my machine,

![image.png](https://images.zenhubusercontent.com/600ae36fc5ce0836e9a11e4b/3d475870-7781-4256-80a7-04cbb5c9849a) 

Which workflow is that?

**Comment by NWalker4483** [comment]
![image.png](https://images.zenhubusercontent.com/600ae36fc5ce0836e9a11e4b/d5d3fbdb-3552-413a-82cd-dbf2ba4faff9)

**Comment by calexh-sar** [comment]
@NWalker4483 Dan released this code to production last night and not working there.  I am using the Chrome browser, in case that is part of the problem.  The other thing I see is that I used a help (info button) Property on a Form Field, not in the Element Documentation, for my testing.

I did give the Element Documentation a try this time, and what I am seeing is that nothing has the focus, but if I tab, the link in the body of the message gets focus first and the OK button next.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/55d4c721-c041-4313-b96e-47efea093a33)

**Comment by calexh-sar** [comment]
@NWalker4483 the focus appears to still on the first clickable item in the dialog box and not the OK button.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/94f68507-111b-407e-aa68-b227e57b9815)

**Comment by calexh-sar** [comment]
@NWalker4483 I am checking tickets in Ready for Release per discussion with Dan in which he said that there is noting pending for him to release and code for all tickets should be available in testing.

If this is indeed the case, this issue is still not fixed.

**Comment by calexh-sar** [comment]
@NWalker4483 has the fix for this been released?  It currently seems to be working as designed.

**Comment by NWalker4483** [comment]
Yes, I think this ticket can be closed

**Comment by calexh-sar** [comment]
Working as designed
