### ISSUE TITLE
hide_expression not working in DSP Repeating Section

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#636]
In the Data Security Plan workflow, the _Enter HIPAA Identifiers_ User Task on the `qualifiers` Form Filed.  In the case shown below, it should not be hidden.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8d83b8b9-bb89-46d0-8fe0-b55c3fec41ab)

**Note:** Similar problem with the _Enter Individual Use Devices_ User Task

**Comment by Leashys** [comment]
My note on this one is to change the hide expression of the second field to `identifier == 'HIPAA_Ids0'`
