### ISSUE TITLE
Study Status Updates

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#653]
Change _Open to Enrollment_ to _IRB Open to Enrollment_.  

Add new study status: _CRConnect Complete_

Update Main Dashboard UI and reset order to: _In Progress_, _IRB Open to Enrollment_., _CRConnect Complete_, _Hold_, _Abandoned_

Studies should be editable in the _In Progress_, _IRB Open to Enrollment_. and _CRConnect Complete_ statuses.

Add `set_study_status()` script to be able to set study status programmatically.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/88c391b4-883e-4b72-9e8f-96bb24e80d74)

**Comment by cullerton** [comment]
@calexh-sar You mentioned possibly breaking this ticket into multiple tickets.
It'd be nice to break out this one.
Studies should be editable in the In Progress, IRB Open to Enrollment. and CRConnect Complete statuses.

**Comment by cullerton** [comment]
2 parts of this are complete:
- Add new study status: CRConnect Complete 
- Add set_study_status() script to be able to set study status programmatically.

(CRConnect_Complete is 'cr_connect_complete' in the StudyStatus model)

**Comment by calexh-sar** [comment]
Moving back to Backlog and assigning to Alicia for the UI updates in the Main Dashboard

**Comment by calexh-sar** [comment]
@Leashys would you please remove the space between CR and Connect
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/432934f5-f076-4807-8cc8-aa0f8128f567)

**Comment by calexh-sar** [comment]
@Leashys if I am correct that this is #5 in Dan's list of what was just released, I am still seeing the space:![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/67d134ec-1b47-484d-90f8-eac545867f08)

**Comment by calexh-sar** [comment]
Done, was a release issue.
