### ISSUE TITLE
Validating Associates

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#659]
We get errors validating workflow with associates because we don't seed good mock data.
We should:
- Use study data when a study is selected
- Seed good mock data when we don't select a study

**Comment by calexh-sar** [comment]
@cullerton I just attempted to validate the Department Chair workflow and received this error:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/e71a8da5-6fa2-448d-8d8b-619136353b3e)

A search for dc_uid in the Task Data returns nothing.  

The workflow paths, i.e., accept the current DC and specify a proxy for the current DC, run successfully in the app and dc_uid. was available:
![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8a8fabac-35ea-4b3d-803c-47ccd0383546)

**Comment by cullerton** [comment]
@calexh-sar Is this still an issue? I thought we worked on this.
Either way, I'm wondering if there's an easy way to display the line in the script that fails. I.e., `del(dc_uid)`
If we do see this error again, let me know, and maybe I can figure that out. 
The error is generated in Spiff

**Comment by calexh-sar** [comment]
Fixed
