### ISSUE TITLE
PDF for IRB Document Submission Form

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#660]
When documents are zipped and sent to the IRB for Pre-Review Submission, a Document Submission form is created as well and sent with the zipped files.  The IRB as requested that the Document Submission Form be in PDF format.  We can create a Word doc and have them manually resave it as a PDF.  But first, would like to know if that option is programmatically available in the script file we currently use or a quick add-on.

**Comment by calexh-sar** [comment]
Here is the approved draft of the Word doc they want in PDF format:
[https://app.zenhub.com/files/223421082/a425e220-1b30-4bd6-81a9-6d2d07a9c81a/download](https://app.zenhub.com/files/223421082/a425e220-1b30-4bd6-81a9-6d2d07a9c81a/download)

And the PDF format version as saved from Word:
[https://app.zenhub.com/files/223421082/9a51df05-e18c-4414-88ba-4d089ba57832/download](https://app.zenhub.com/files/223421082/9a51df05-e18c-4414-88ba-4d089ba57832/download)

**Comment by cullerton** [comment]
The best answer may be for them to generate the PDF on their local machine, and upload it to CR Connect

**Comment by calexh-sar** [comment]
Thanks for checking, will let them know and adjust the workflow accordingly.
