### ISSUE TITLE
Orgs / Orgs_Info - Can't handle unmatched organization

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#663]
When validating the Study Information Workflow, with the PI of 'kch7d' who has an organization code of "
E1:UPG-MD-NEUR Neurology, E0:MD-NEUR Neurology"

If I say that the organization was NOT found,  I get this error:
Gateway_0pf5p2c: Error evaluating expression 'len(enum_variations) > 1', name 'enum_variations' is not defined

It look like the orgs_select_org.bpmn, the **org_name** gets set to "MD" which is not matched in the Decision Table, and the enum_variations is set up null.

I guess there are two problems - 1) we should handle when we can't find an organization (maybe log an error message and show them a screen telling them to contact technical support  and 2) We should re-work the praser to better pull out the Neurology term.

Here are some of the variables I see, in case this helps with debugging:
"e0_deptAbbrv": "NEUR",
  "e0_dept_start": 3,
  "e0_first_comma": -1,
  "e0_first_hyphen": 2,
  "e0_first_space": 7,
  "e0_org": "MD-NEUR Neurology",
  "e0_schoolAbbrv": "MD",
  "e0_specName": "Neurology",
  "e0_spec_end": 17,
  "e0_spec_start": 8,
  "e0_start": 29,

**Comment by calexh-sar** [comment]
Closing this ticket since the alternative org search option was disabled.
