### ISSUE TITLE
Update get_workflow_status() to key off of workflow_spec_id

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#664]
Update the `get_workflow_status()` script to key off of `workflow_spec_id` instead of `workflow_id` since the latter can change.

**Comment by calexh-sar** [comment]
@cullerton would you please provide the current list of workflow statuses this script could return.

**Comment by cullerton** [comment]
@calexh-sar 

class WorkflowStatus(enum.Enum):
    not_started = "not_started"
    user_input_required = "user_input_required"
    waiting = "waiting"
    complete = "complete"
    erroring = "erroring"

**Comment by calexh-sar** [comment]
Working as designed
