### ISSUE TITLE
Approvals Error for Department Chair

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#666]
Looks like it is possible to get through the Associates Get Department Chair without finding a UID for the Department Chair.  But the Appovals Get Approval Info script expects there to be a dc_uid if approver_cid == "Department Chair", but that does not seem to be the case.

**I can produce this error when validating the Department Chair Approval Workflow:**
Error Details:
File: approvals_get_approval_info.bpmn
Set Approver CId(s) (Activity_1dp0ho7)
Line #: 5
Activity_1dp0ho7: something you are referencing does not exist: "name 'dc_uid' is not defined". Did you mean '['dc_info', 'ae_name', 'dc_status']'?
Error on line #5
Approvers = dc_uid

**Comment by calexh-sar** [comment]
@danfunk this is one of the validation errors which resulted in #659.  Please let me know if this is not the case.

**Comment by calexh-sar** [comment]
Mike found fixed, need to release and  test.

**Comment by calexh-sar** [comment]
Fixed
