### ISSUE TITLE
Validate Lane Variables

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#667]
We handle swim lanes by checking the name of the lane evaluating it against the task data.  For instance the line might be called "approvers" in which case, there should be an array of values (or a single string) in the task data called "Approvers" and in it, should be a list if UVA uids ('dhf8r' for example).  

During validation we should assure that the variable exists in the task data, and that it contains a string or a list of strings that are uva user ids. We could go so far as to assure that these are valid ids in LDAP, and this might not be a bad idea.

**Comment by cullerton** [comment]
Instead of ensuring that the data exists, we raise an error so the configurator knows the problem exists.
