### ISSUE TITLE
Checkboxes should always have a default of False

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#671]
Boolean form fields show up as yes/no radio buttons by default.  Checkboxes are a special case of boolean for form fields, it's set a property on the field.  It is reasonable to say that not checking a checkbox, is itself an action, and that we should capture that as False rather than null.   So assure that in BOTH backend validation, and in the front end, that we interpret an unchecked checkbox as false.

**Comment by cullerton** [comment]
@Leashys Here's another one where you can school me. 
The validation part already works, and I'm hoping you can show me where in the front end we can set this default.
I already have a workflow and failing test in the backend looking for False

**Comment by cullerton** [comment]
FYI
Currently, in validation, there is no such thing as an unchecked checkbox. We always pick True or False 
`return random.choice([True, False])`
