### ISSUE TITLE
Hide Category

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#679]
Provide a means to programmatically hide and unhide a Category.  This will primarily be use to hide the _IRB Submission_ Category until the study is ready to submit for Pre-Review.

**Comment by calexh-sar** [comment]
@Leashys would you please update the wiki with information on how to implement this feature.

**Comment by Leashys** [comment]
https://github.com/sartography/cr-connect-bpmn/wiki/Dictionary-Output-from-Decision-Tables#using-decision-tables-to-describe-workflow-and-category-status
Here you go :)

**Comment by calexh-sar** [comment]
Thanks, @Leashys
