### ISSUE TITLE
Logging Tab UI Tweak

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#683]
Let's take whatever width is needed to allow the Category name _UVA Compliance Reviews for IRB_  fit on on e line from the Workflow column.  

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/9fe08ade-b417-445c-8c50-c7a919ae71d0)

**Comment by calexh-sar** [comment]
Working as designed, but going to repurpose this ticket to see if we can get one more tweak back in the other direction.  Can we take back a bit from Category and add to Workflow so we don't wrap there.  The longest current workflow name is: IRB Approved with Conditions Status Check

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/8bd34d2d-f02f-429c-98b2-1dac2d6a1823)

**Comment by cullerton** [comment]
Here's my latest attempt.
![Screen Shot 2022-05-10 at 4.16.36 PM.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/bfb2caa5-f859-44d2-81fb-9a2c907ade9d)

**Comment by calexh-sar** [comment]
Working as designed
