### ISSUE TITLE
IRB Info IRB_REVIEW_TYPE Update

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#689]
Update the IRB Info IRB_REVIEW_TYPE field in PB Mock so it is a dropdown with the same text values found in the IRB Details REVIEW_TYPE field.  

Notes:
1. The [IRB Info API](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=currentIRBInfo&studyid=12412) returns only text for the Review Type: `"IRB_REVIEW_TYPE":"Full Committee"`and the [IRB Details API](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=Study&studyid=12412) returns both the numeric code for the Review Type and text: `"REVIEW_TYPE":2,"REVIEWTYPENAME":"Full Committee"'
1. The fields `"REVIEW_TYPE"` amd `"REVIEWTYPENAME"` are not shown in the Schema section of the [IRB Info API](https://hrpp.irb.virginia.edu/webservices/crconnect/crconnect.cfc?method=currentIRBInfo&studyid=12412).

**Comment by cullerton** [comment]
I accidently made this change directly in dev branch of PB Mock
2 files edited; forms.py and test_sanity.py
In my defense, I did create a branch in cr-connect-workflow :)

**Comment by calexh-sar** [comment]
Working as designed
