### ISSUE TITLE
Document Links Not Working on Staging

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#696]
Clicking on document links on stating do not result in the document being downloaded.  Clicking on the links in the Document Pane does download the document.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/c912074f-1143-49ba-8639-2290563610d7)

This is working on testing,

**Comment by cullerton** [comment]
@calexh-sar Is this still an issue for you. This just worked on staging for me.

**Comment by cullerton** [comment]
I did some more testing.
- If I use Firefox, download always works--whether I view as me or Kirsten (kb8wj)
- If I use Chrome, download works for me but fails when I view as Kirsten

**Comment by cullerton** [comment]
I noticed the urls on testing are HTTPS, while staging is HTTP.
Unsure if this is the cause

**Comment by calexh-sar** [comment]
@danfunk Are Mike and I remembering correctly that you need to work with Neal to get this fixed?

**Comment by calexh-sar** [comment]
Fixed
