### ISSUE TITLE
Update PB Mock IRB Info

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#703]
The IRB Info API endpoint returns a dictionary when a study is **not** already downloaded to IRB Online

`
{
    "STATUS": "Error",
    "DETAIL": "Study not downloaded to IRB Online."
 }
`

and a list with a dictionary when a study **is** downloaded to IRB Online

`
   [ {
      "UVA_STUDY_TRACKING": "HSR210056",
      "DATE_MODIFIED": "April, 05 2021 14:02:00",
      "IRB_ADMINISTRATIVE_REVIEWER": "Eileen Sembrowich (ecs3b)",
      "AGENDA_DATE": null,
      "IRB_REVIEW_TYPE": "Non-UVA IRB - Full Board",
      "IRBEVENT": "Administrative Review Complete – Non-UVA IRB",
      "IRB_STATUS": "Open to Enrollment",
      "IRB_OF_RECORD": "Advarra",
      "UVA_IRB_HSR_IS_IRB_OF_RECORD_FOR_ALL_SITES": 0,
      "SS_STUDY_ID": 16387,
      "STUDYIRBREVIEWERADMIN": null,
      "STATUS": "Downloaded",
      "DETAIL": "Study downloaded to IRB Online."
    }]
`

Also, we need to 
- add STATUS and DETAIL
- fix our date field to look like theirs
  - ours: "DATE_MODIFIED": "2021-04-20T00:00:00+00:00"
  - theirs: "DATE_MODIFIED": "April, 05 2021 14:02:00"

**Comment by calexh-sar** [comment]
Working as designed
