### ISSUE TITLE
Environment Instance Variable

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#729]
Provide a script which returns the current environment instance, e.g., Testing, Staging, Training, Production, etc., that can be used to adjust other variables, such as timer durations, which often are different in each environment.  If possible, would be beneficial if this script could be run within a DMN table, but not a hard requirement if difficult.

**Comment by cullerton** [comment]
Updated the Wiki
https://github.com/sartography/cr-connect-bpmn/wiki/Script-Tasks#get-instance

**Comment by calexh-sar** [comment]
Working as designed
