### ISSUE TITLE
Auto-assign Workflow spec display order

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#74]
The Configurator is prompted for the display order when adding a new Workflow Specification.  It is confusing as to how to determine what should be entered.Just auto-assign the bottom position and let them use the arrows to reposition, if needed.

**Comment by calexh-sar** [comment]
@cullerton the Configurator is still prompted for the Display Order when adding a new Workflow Specification.

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/ea12db22-9563-4ed1-835a-955947f85d0a)

**Comment by cullerton** [comment]
@calexh-sar This happens on the front end.

**Comment by calexh-sar** [comment]
@NWalker4483 is this a ticket you would be able to work on while you are in the area with ticket #260

**Comment by NWalker4483** [comment]
Sure should be quick

**Comment by NWalker4483** [comment]
Should I remove it for when creating a new workflow category also?

**Comment by NWalker4483** [comment]
Can I start closing these?

**Comment by cullerton** [comment]
This is still an issue on testing.

<img width="1729" alt="Screen Shot 2021-04-08 at 10 11 10 AM" src="https://user-images.githubusercontent.com/1569935/114041473-93d6cc00-9852-11eb-86ea-30032734d139.png">

**Comment by calexh-sar** [comment]
Working as designed.
