### ISSUE TITLE
Git permission issue

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#741]
Getting a permission issue using git on testing

![image.png](https://images.zenhubusercontent.com/5fa55f08b2891e7cfdfd2ed0/e4b1de85-4ddf-420e-afd5-fd0591f5a248)

It might be related to GitHub tokens expiring. 

Need to find a good solution for this.

**Comment by cullerton** [comment]
GitPython stores user and pass in .git/config

**Comment by calexh-sar** [comment]
Fixed
