### ISSUE TITLE
Git wonkiness

### ISSUE THREAD

**Issue by cullerton** [sartography/cr-connect#747]
We had a Publish fail when an authentication token expired.
This caused staging branch of crconnect-workflow-specs to get out of sync

Then I tried to Publish on staging and the commit worked but the push never happened.
No error.
This should happen on the back end in GitService.push_to_remote

Just need to make sure things are working correctly.

**Comment by cullerton** [comment]
I did not have to make any code changes.
Only git command line stuff
Testing could not do a push, because it was not up to date with the remote.
I had to do a git pull, then a git push.

**Comment by cullerton** [comment]
@calexh-sar I will put this in Configuration/QA to make sure it works for you before closing the ticket

**Comment by calexh-sar** [comment]
Fixed
