### ISSUE TITLE
Nav Menu options beyond Exclusive Gateway Return Error

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#76]
When entering the DSP workflow for the first time the nave menu options for the three tasks beyond the Outside of UVA Exclusive Gateway are visible.
![image](https://user-images.githubusercontent.com/54854669/86640798-9e54f400-bfa8-11ea-8aca-c22127cb7d70.png)
If one is selected, is returns an error
![image](https://user-images.githubusercontent.com/54854669/86641008-ce03fc00-bfa8-11ea-8ae8-511687898440.png)
We hide those menu options if the response to the gateway question is "No".  If we don't want to do the same if no response has been provided yet, at the least we should disable them.

**Comment by danfunk** [comment]
@w4kpm - Just verified this is still an issue.  Looks like these tasks have a state of 'MAYBE', which should not be clickable - a modification to the front end should resolve this problem @ajlouie

**Comment by calexh-sar** [comment]
@danfunk I moved this ticket over to the Icebox lane pending outcome of the Design for Concept review to see if the current design around tasks after Exclusive Gateways survives.  I can move this back to the Backlog if you think it is important enough to do and/or @ajlouie says it is a quick fix we should just knock out.

**Comment by danfunk** [comment]
We've reworked the hell out of nav, no longer applicable.
