### ISSUE TITLE
IRB_STATUS Update in PB Mock

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#763]
I discovered today that the IRB_STATUS we currently have "Open to enrollment" should be "Open to Enrollment" (Enrollment capitalized).

![image.png](https://images.zenhubusercontent.com/5f0623d8a1d620a9f39301dc/b7f49be5-73fd-41a6-b905-2ac1cdc984cb)

Please update this in the PB Mock so it returns "Open to Enrollment"

Also, I have attempted to find all places in the my BPMN diagrams that need to be changed, but if there is a way to programmatically check for "Open to enrollment", that would be helpful.  I don't need them programmatically updated, unless that is easy and safe to do.

Note that we also use "open to enrollment" as a Study Status.  Those should remain unchanged.

**Comment by cullerton** [comment]
The branch for this ticket includes a migration, so the DB values should be correct after the build.
You can always select the new value on the edit_info page for any studies that lose their value.

**Comment by calexh-sar** [comment]
Working as designed
