### ISSUE TITLE
Dashboard for Approvers

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#91]
When an approver signs in, they should see any pending approval in the order they were received.  Studies for which they are/were an approver should still be categorized as In Progress, Open for Enrollment, Hold and Abandoned.  Within the In Progress section, the approval status for each study should be noted and segregated.

**Comment by ajlouie** [comment]
Fixed by https://github.com/sartography/cr-connect-frontend/pull/156

**Comment by calexh-sar** [comment]
Working as designed at the time of this ticket.
