### ISSUE TITLE
Place Study into Open for Enrollment Status

### ISSUE THREAD

**Issue by calexh-sar** [sartography/cr-connect#94]
One of the four study status sections in the dashboard is Open for Enrollment. The intent for this state is to allow coordinators to place a study in the Open for Enrollment status, which should move it out of the In Progress section and into the Open for Enrollment section, when the approved study has established a start date.

Provide the coordinator with a means to place the study into Open for Enrollment status by entering the date when the study will start and take it out of Open for Enrollment status and placed back into the In Progress section if that date is no longer valid, although it is unlikely an approved study will be sent back for another round of IRB approval.

Also provide a notes field in that form whose intent is to require the coordinator to record the details regarding a change in state. It should be clear which note goes with which instance of placing the study on hold and returning it to the In Progress section/status.

In this case in addition to recording the timestamp when the status was changed for metrics reporting, the study start date needs to be available for metrics as well.

**Comment by calexh-sar** [comment]
From 08/06 Slack chat with Jason R:

I don't believe Open to Enrollment would ever move back steps since it has been approved and is ready for patients to agree to a trial

correct if I am wrong though

if there is a change in status, it would be a modification which is not something CRC2 would handle

**Comment by calexh-sar** [comment]
Not working as designed.  The dialog box pops up, allows entry and save.  But study remains where in In Progress.

**Comment by calexh-sar** [comment]
Testing on 12/22 and still not working as designed.

**Comment by cullerton** [comment]
I believe this issue is fixed, because of ticket 20.

**Comment by calexh-sar** [comment]
Working as designed.
