### ISSUE TITLE
Validate Form Field Names during Workflow Validation Process

### ISSUE THREAD

**Issue by danfunk** [sartography/cr-connect#96]
Form fields must be valid variable names in both Python and Javascript.
This issue came up with someone created a form field name with a "-" in it, and the javascript evaluated this to be a subtraction operation.  We should assure that all form field names start with a string, and contain only chacacters and underscores.

**Comment by cullerton** [comment]
Do we mean ID? I don't see a name associated with a form field.

**Comment by calexh-sar** [comment]
Working as designed.
